==========================================
rewrite in TASK1 : freshOid(0) createExample(100) .
rewrites: 6601 in 16ms cpu (16ms real) (412536 rewrites/second)
result Configuration: freshOid(2000) createPositive(0) createNegative(0) 
<  0 : Movie | rating : 9.9e+2 > 
<  1 : Movie | rating : 9.91e+2 > 
<  2 : Movie | rating : 9.92e+2 > 
<  3 : Movie | rating : 9.93e+2 > 
<  4 : Movie | rating : 9.94e+2 > 
<  5 : Actor | name : "a990",movies : (0, 1, 2, 3) > 
<  6 : Actor | name : "a991",movies : (0, 1, 2, 3) > 
<  7 : Actor | name : "a992",movies : (1, 2, 3) > 
<  8 : Actress | name : "a993",movies : (1, 2, 3, 4) > 
<  9 : Actress | name : "a994",movies : (1, 2, 3, 4) > 
<  10 : Movie | rating : 9.95e+2 > 
<  11 : Movie | rating : 9.96e+2 > 
<  12 : Movie | rating : 9.97e+2 > 
<  13 : Movie | rating : 9.98e+2 > 
<  14 : Movie | rating : 9.99e+2 > 
<  15 : Actor | name : "a995",movies : (10, 11) > 
<  16 : Actor | name : "a996",movies : (10, 11, 12) > 
<  17 : Actress | name : "a997",movies : (11, 12, 13) > 
<  18 : Actress | name : "a998",movies : (12, 13, 14) > 
<  19 : Actress | name : "a999",movies : (13, 14) > 
<  20 : Movie | rating : 9.8e+2 > 
<  21 : Movie | rating : 9.81e+2 > 
<  22 : Movie | rating : 9.82e+2 > 
<  23 : Movie | rating : 9.83e+2 > 
<  24 : Movie | rating : 9.84e+2 > 
<  25 : Actor | name : "a980",movies : (20, 21, 22, 23) > 
<  26 : Actor | name : "a981",movies : (20, 21, 22, 23) > 
<  27 : Actor | name : "a982",movies : (21, 22, 23) > 
<  28 : Actress | name : "a983",movies : (21, 22, 23, 24) > 
<  29 : Actress | name : "a984",movies : (21, 22, 23, 24) > 
<  30 : Movie | rating : 9.85e+2 > 
<  31 : Movie | rating : 9.86e+2 > 
<  32 : Movie | rating : 9.87e+2 > 
<  33 : Movie | rating : 9.88e+2 > 
<  34 : Movie | rating : 9.89e+2 > 
<  35 : Actor | name : "a985",movies : (30, 31) > 
<  36 : Actor | name : "a986",movies : (30, 31, 32) > 
<  37 : Actress | name : "a987",movies : (31, 32, 33) > 
<  38 : Actress | name : "a988",movies : (32, 33, 34) > 
<  39 : Actress | name : "a989",movies : (33, 34) > 
<  40 : Movie | rating : 9.7e+2 > 
<  41 : Movie | rating : 9.71e+2 > 
<  42 : Movie | rating : 9.72e+2 > 
<  43 : Movie | rating : 9.73e+2 > 
<  44 : Movie | rating : 9.74e+2 > 
<  45 : Actor | name : "a970",movies : (40, 41, 42, 43) > 
<  46 : Actor | name : "a971",movies : (40, 41, 42, 43) > 
<  47 : Actor | name : "a972",movies : (41, 42, 43) > 
<  48 : Actress | name : "a973",movies : (41, 42, 43, 44) > 
<  49 : Actress | name : "a974",movies : (41, 42, 43, 44) > 
<  50 : Movie | rating : 9.75e+2 > 
<  51 : Movie | rating : 9.76e+2 > 
<  52 : Movie | rating : 9.77e+2 > 
<  53 : Movie | rating : 9.78e+2 > 
<  54 : Movie | rating : 9.79e+2 > 
<  55 : Actor | name : "a975",movies : (50, 51) > 
<  56 : Actor | name : "a976",movies : (50, 51, 52) > 
<  57 : Actress | name : "a977",movies : (51, 52, 53) > 
<  58 : Actress | name : "a978",movies : (52, 53, 54) > 
<  59 : Actress | name : "a979",movies : (53, 54) > 
<  60 : Movie | rating : 9.6e+2 > 
<  61 : Movie | rating : 9.61e+2 > 
<  62 : Movie | rating : 9.62e+2 > 
<  63 : Movie | rating : 9.63e+2 > 
<  64 : Movie | rating : 9.64e+2 > 
<  65 : Actor | name : "a960",movies : (60, 61, 62, 63) > 
<  66 : Actor | name : "a961",movies : (60, 61, 62, 63) > 
<  67 : Actor | name : "a962",movies : (61, 62, 63) > 
<  68 : Actress | name : "a963",movies : (61, 62, 63, 64) > 
<  69 : Actress | name : "a964",movies : (61, 62, 63, 64) > 
<  70 : Movie | rating : 9.65e+2 > 
<  71 : Movie | rating : 9.66e+2 > 
<  72 : Movie | rating : 9.67e+2 > 
<  73 : Movie | rating : 9.68e+2 > 
<  74 : Movie | rating : 9.69e+2 > 
<  75 : Actor | name : "a965",movies : (70, 71) > 
<  76 : Actor | name : "a966",movies : (70, 71, 72) > 
<  77 : Actress | name : "a967",movies : (71, 72, 73) > 
<  78 : Actress | name : "a968",movies : (72, 73, 74) > 
<  79 : Actress | name : "a969",movies : (73, 74) > 
<  80 : Movie | rating : 9.5e+2 > 
<  81 : Movie | rating : 9.51e+2 > 
<  82 : Movie | rating : 9.52e+2 > 
<  83 : Movie | rating : 9.53e+2 > 
<  84 : Movie | rating : 9.54e+2 > 
<  85 : Actor | name : "a950",movies : (80, 81, 82, 83) > 
<  86 : Actor | name : "a951",movies : (80, 81, 82, 83) > 
<  87 : Actor | name : "a952",movies : (81, 82, 83) > 
<  88 : Actress | name : "a953",movies : (81, 82, 83, 84) > 
<  89 : Actress | name : "a954",movies : (81, 82, 83, 84) > 
<  90 : Movie | rating : 9.55e+2 > 
<  91 : Movie | rating : 9.56e+2 > 
<  92 : Movie | rating : 9.57e+2 > 
<  93 : Movie | rating : 9.58e+2 > 
<  94 : Movie | rating : 9.59e+2 > 
<  95 : Actor | name : "a955",movies : (90, 91) > 
<  96 : Actor | name : "a956",movies : (90, 91, 92) > 
<  97 : Actress | name : "a957",movies : (91, 92, 93) > 
<  98 : Actress | name : "a958",movies : (92, 93, 94) > 
<  99 : Actress | name : "a959",movies : (93, 94) > 
<  100 : Movie | rating : 9.4e+2 > 
<  101 : Movie | rating : 9.41e+2 > 
<  102 : Movie | rating : 9.42e+2 > 
<  103 : Movie | rating : 9.43e+2 > 
<  104 : Movie | rating : 9.44e+2 > 
<  105 : Actor | name : "a940",movies : (100, 101, 102, 103) > 
<  106 : Actor | name : "a941",movies : (100, 101, 102, 103) > 
<  107 : Actor | name : "a942",movies : (101, 102, 103) > 
<  108 : Actress | name : "a943",movies : (101, 102, 103, 104) > 
<  109 : Actress | name : "a944",movies : (101, 102, 103, 104) > 
<  110 : Movie | rating : 9.45e+2 > 
<  111 : Movie | rating : 9.46e+2 > 
<  112 : Movie | rating : 9.47e+2 > 
<  113 : Movie | rating : 9.48e+2 > 
<  114 : Movie | rating : 9.49e+2 > 
<  115 : Actor | name : "a945",movies : (110, 111) > 
<  116 : Actor | name : "a946",movies : (110, 111, 112) > 
<  117 : Actress | name : "a947",movies : (111, 112, 113) > 
<  118 : Actress | name : "a948",movies : (112, 113, 114) > 
<  119 : Actress | name : "a949",movies : (113, 114) > 
<  120 : Movie | rating : 9.3e+2 > 
<  121 : Movie | rating : 9.31e+2 > 
<  122 : Movie | rating : 9.32e+2 > 
<  123 : Movie | rating : 9.33e+2 > 
<  124 : Movie | rating : 9.34e+2 > 
<  125 : Actor | name : "a930",movies : (120, 121, 122, 123) > 
<  126 : Actor | name : "a931",movies : (120, 121, 122, 123) > 
<  127 : Actor | name : "a932",movies : (121, 122, 123) > 
<  128 : Actress | name : "a933",movies : (121, 122, 123, 124) > 
<  129 : Actress | name : "a934",movies : (121, 122, 123, 124) > 
<  130 : Movie | rating : 9.35e+2 > 
<  131 : Movie | rating : 9.36e+2 > 
<  132 : Movie | rating : 9.37e+2 > 
<  133 : Movie | rating : 9.38e+2 > 
<  134 : Movie | rating : 9.39e+2 > 
<  135 : Actor | name : "a935",movies : (130, 131) > 
<  136 : Actor | name : "a936",movies : (130, 131, 132) > 
<  137 : Actress | name : "a937",movies : (131, 132, 133) > 
<  138 : Actress | name : "a938",movies : (132, 133, 134) > 
<  139 : Actress | name : "a939",movies : (133, 134) > 
<  140 : Movie | rating : 9.2e+2 > 
<  141 : Movie | rating : 9.21e+2 > 
<  142 : Movie | rating : 9.22e+2 > 
<  143 : Movie | rating : 9.23e+2 > 
<  144 : Movie | rating : 9.24e+2 > 
<  145 : Actor | name : "a920",movies : (140, 141, 142, 143) > 
<  146 : Actor | name : "a921",movies : (140, 141, 142, 143) > 
<  147 : Actor | name : "a922",movies : (141, 142, 143) > 
<  148 : Actress | name : "a923",movies : (141, 142, 143, 144) > 
<  149 : Actress | name : "a924",movies : (141, 142, 143, 144) > 
<  150 : Movie | rating : 9.25e+2 > 
<  151 : Movie | rating : 9.26e+2 > 
<  152 : Movie | rating : 9.27e+2 > 
<  153 : Movie | rating : 9.28e+2 > 
<  154 : Movie | rating : 9.29e+2 > 
<  155 : Actor | name : "a925",movies : (150, 151) > 
<  156 : Actor | name : "a926",movies : (150, 151, 152) > 
<  157 : Actress | name : "a927",movies : (151, 152, 153) > 
<  158 : Actress | name : "a928",movies : (152, 153, 154) > 
<  159 : Actress | name : "a929",movies : (153, 154) > 
<  160 : Movie | rating : 9.1e+2 > 
<  161 : Movie | rating : 9.11e+2 > 
<  162 : Movie | rating : 9.12e+2 > 
<  163 : Movie | rating : 9.13e+2 > 
<  164 : Movie | rating : 9.14e+2 > 
<  165 : Actor | name : "a910",movies : (160, 161, 162, 163) > 
<  166 : Actor | name : "a911",movies : (160, 161, 162, 163) > 
<  167 : Actor | name : "a912",movies : (161, 162, 163) > 
<  168 : Actress | name : "a913",movies : (161, 162, 163, 164) > 
<  169 : Actress | name : "a914",movies : (161, 162, 163, 164) > 
<  170 : Movie | rating : 9.15e+2 > 
<  171 : Movie | rating : 9.16e+2 > 
<  172 : Movie | rating : 9.17e+2 > 
<  173 : Movie | rating : 9.18e+2 > 
<  174 : Movie | rating : 9.19e+2 > 
<  175 : Actor | name : "a915",movies : (170, 171) > 
<  176 : Actor | name : "a916",movies : (170, 171, 172) > 
<  177 : Actress | name : "a917",movies : (171, 172, 173) > 
<  178 : Actress | name : "a918",movies : (172, 173, 174) > 
<  179 : Actress | name : "a919",movies : (173, 174) > 
<  180 : Movie | rating : 9.0e+2 > 
<  181 : Movie | rating : 9.01e+2 > 
<  182 : Movie | rating : 9.02e+2 > 
<  183 : Movie | rating : 9.03e+2 > 
<  184 : Movie | rating : 9.04e+2 > 
<  185 : Actor | name : "a900",movies : (180, 181, 182, 183) > 
<  186 : Actor | name : "a901",movies : (180, 181, 182, 183) > 
<  187 : Actor | name : "a902",movies : (181, 182, 183) > 
<  188 : Actress | name : "a903",movies : (181, 182, 183, 184) > 
<  189 : Actress | name : "a904",movies : (181, 182, 183, 184) > 
<  190 : Movie | rating : 9.05e+2 > 
<  191 : Movie | rating : 9.06e+2 > 
<  192 : Movie | rating : 9.07e+2 > 
<  193 : Movie | rating : 9.08e+2 > 
<  194 : Movie | rating : 9.09e+2 > 
<  195 : Actor | name : "a905",movies : (190, 191) > 
<  196 : Actor | name : "a906",movies : (190, 191, 192) > 
<  197 : Actress | name : "a907",movies : (191, 192, 193) > 
<  198 : Actress | name : "a908",movies : (192, 193, 194) > 
<  199 : Actress | name : "a909",movies : (193, 194) > 
<  200 : Movie | rating : 8.9e+2 > 
<  201 : Movie | rating : 8.91e+2 > 
<  202 : Movie | rating : 8.92e+2 > 
<  203 : Movie | rating : 8.93e+2 > 
<  204 : Movie | rating : 8.94e+2 > 
<  205 : Actor | name : "a890",movies : (200, 201, 202, 203) > 
<  206 : Actor | name : "a891",movies : (200, 201, 202, 203) > 
<  207 : Actor | name : "a892",movies : (201, 202, 203) > 
<  208 : Actress | name : "a893",movies : (201, 202, 203, 204) > 
<  209 : Actress | name : "a894",movies : (201, 202, 203, 204) > 
<  210 : Movie | rating : 8.95e+2 > 
<  211 : Movie | rating : 8.96e+2 > 
<  212 : Movie | rating : 8.97e+2 > 
<  213 : Movie | rating : 8.98e+2 > 
<  214 : Movie | rating : 8.99e+2 > 
<  215 : Actor | name : "a895",movies : (210, 211) > 
<  216 : Actor | name : "a896",movies : (210, 211, 212) > 
<  217 : Actress | name : "a897",movies : (211, 212, 213) > 
<  218 : Actress | name : "a898",movies : (212, 213, 214) > 
<  219 : Actress | name : "a899",movies : (213, 214) > 
<  220 : Movie | rating : 8.8e+2 > 
<  221 : Movie | rating : 8.81e+2 > 
<  222 : Movie | rating : 8.82e+2 > 
<  223 : Movie | rating : 8.83e+2 > 
<  224 : Movie | rating : 8.84e+2 > 
<  225 : Actor | name : "a880",movies : (220, 221, 222, 223) > 
<  226 : Actor | name : "a881",movies : (220, 221, 222, 223) > 
<  227 : Actor | name : "a882",movies : (221, 222, 223) > 
<  228 : Actress | name : "a883",movies : (221, 222, 223, 224) > 
<  229 : Actress | name : "a884",movies : (221, 222, 223, 224) > 
<  230 : Movie | rating : 8.85e+2 > 
<  231 : Movie | rating : 8.86e+2 > 
<  232 : Movie | rating : 8.87e+2 > 
<  233 : Movie | rating : 8.88e+2 > 
<  234 : Movie | rating : 8.89e+2 > 
<  235 : Actor | name : "a885",movies : (230, 231) > 
<  236 : Actor | name : "a886",movies : (230, 231, 232) > 
<  237 : Actress | name : "a887",movies : (231, 232, 233) > 
<  238 : Actress | name : "a888",movies : (232, 233, 234) > 
<  239 : Actress | name : "a889",movies : (233, 234) > 
<  240 : Movie | rating : 8.7e+2 > 
<  241 : Movie | rating : 8.71e+2 > 
<  242 : Movie | rating : 8.72e+2 > 
<  243 : Movie | rating : 8.73e+2 > 
<  244 : Movie | rating : 8.74e+2 > 
<  245 : Actor | name : "a870",movies : (240, 241, 242, 243) > 
<  246 : Actor | name : "a871",movies : (240, 241, 242, 243) > 
<  247 : Actor | name : "a872",movies : (241, 242, 243) > 
<  248 : Actress | name : "a873",movies : (241, 242, 243, 244) > 
<  249 : Actress | name : "a874",movies : (241, 242, 243, 244) > 
<  250 : Movie | rating : 8.75e+2 > 
<  251 : Movie | rating : 8.76e+2 > 
<  252 : Movie | rating : 8.77e+2 > 
<  253 : Movie | rating : 8.78e+2 > 
<  254 : Movie | rating : 8.79e+2 > 
<  255 : Actor | name : "a875",movies : (250, 251) > 
<  256 : Actor | name : "a876",movies : (250, 251, 252) > 
<  257 : Actress | name : "a877",movies : (251, 252, 253) > 
<  258 : Actress | name : "a878",movies : (252, 253, 254) > 
<  259 : Actress | name : "a879",movies : (253, 254) > 
<  260 : Movie | rating : 8.6e+2 > 
<  261 : Movie | rating : 8.61e+2 > 
<  262 : Movie | rating : 8.62e+2 > 
<  263 : Movie | rating : 8.63e+2 > 
<  264 : Movie | rating : 8.64e+2 > 
<  265 : Actor | name : "a860",movies : (260, 261, 262, 263) > 
<  266 : Actor | name : "a861",movies : (260, 261, 262, 263) > 
<  267 : Actor | name : "a862",movies : (261, 262, 263) > 
<  268 : Actress | name : "a863",movies : (261, 262, 263, 264) > 
<  269 : Actress | name : "a864",movies : (261, 262, 263, 264) > 
<  270 : Movie | rating : 8.65e+2 > 
<  271 : Movie | rating : 8.66e+2 > 
<  272 : Movie | rating : 8.67e+2 > 
<  273 : Movie | rating : 8.68e+2 > 
<  274 : Movie | rating : 8.69e+2 > 
<  275 : Actor | name : "a865",movies : (270, 271) > 
<  276 : Actor | name : "a866",movies : (270, 271, 272) > 
<  277 : Actress | name : "a867",movies : (271, 272, 273) > 
<  278 : Actress | name : "a868",movies : (272, 273, 274) > 
<  279 : Actress | name : "a869",movies : (273, 274) > 
<  280 : Movie | rating : 8.5e+2 > 
<  281 : Movie | rating : 8.51e+2 > 
<  282 : Movie | rating : 8.52e+2 > 
<  283 : Movie | rating : 8.53e+2 > 
<  284 : Movie | rating : 8.54e+2 > 
<  285 : Actor | name : "a850",movies : (280, 281, 282, 283) > 
<  286 : Actor | name : "a851",movies : (280, 281, 282, 283) > 
<  287 : Actor | name : "a852",movies : (281, 282, 283) > 
<  288 : Actress | name : "a853",movies : (281, 282, 283, 284) > 
<  289 : Actress | name : "a854",movies : (281, 282, 283, 284) > 
<  290 : Movie | rating : 8.55e+2 > 
<  291 : Movie | rating : 8.56e+2 > 
<  292 : Movie | rating : 8.57e+2 > 
<  293 : Movie | rating : 8.58e+2 > 
<  294 : Movie | rating : 8.59e+2 > 
<  295 : Actor | name : "a855",movies : (290, 291) > 
<  296 : Actor | name : "a856",movies : (290, 291, 292) > 
<  297 : Actress | name : "a857",movies : (291, 292, 293) > 
<  298 : Actress | name : "a858",movies : (292, 293, 294) > 
<  299 : Actress | name : "a859",movies : (293, 294) > 
<  300 : Movie | rating : 8.4e+2 > 
<  301 : Movie | rating : 8.41e+2 > 
<  302 : Movie | rating : 8.42e+2 > 
<  303 : Movie | rating : 8.43e+2 > 
<  304 : Movie | rating : 8.44e+2 > 
<  305 : Actor | name : "a840",movies : (300, 301, 302, 303) > 
<  306 : Actor | name : "a841",movies : (300, 301, 302, 303) > 
<  307 : Actor | name : "a842",movies : (301, 302, 303) > 
<  308 : Actress | name : "a843",movies : (301, 302, 303, 304) > 
<  309 : Actress | name : "a844",movies : (301, 302, 303, 304) > 
<  310 : Movie | rating : 8.45e+2 > 
<  311 : Movie | rating : 8.46e+2 > 
<  312 : Movie | rating : 8.47e+2 > 
<  313 : Movie | rating : 8.48e+2 > 
<  314 : Movie | rating : 8.49e+2 > 
<  315 : Actor | name : "a845",movies : (310, 311) > 
<  316 : Actor | name : "a846",movies : (310, 311, 312) > 
<  317 : Actress | name : "a847",movies : (311, 312, 313) > 
<  318 : Actress | name : "a848",movies : (312, 313, 314) > 
<  319 : Actress | name : "a849",movies : (313, 314) > 
<  320 : Movie | rating : 8.3e+2 > 
<  321 : Movie | rating : 8.31e+2 > 
<  322 : Movie | rating : 8.32e+2 > 
<  323 : Movie | rating : 8.33e+2 > 
<  324 : Movie | rating : 8.34e+2 > 
<  325 : Actor | name : "a830",movies : (320, 321, 322, 323) > 
<  326 : Actor | name : "a831",movies : (320, 321, 322, 323) > 
<  327 : Actor | name : "a832",movies : (321, 322, 323) > 
<  328 : Actress | name : "a833",movies : (321, 322, 323, 324) > 
<  329 : Actress | name : "a834",movies : (321, 322, 323, 324) > 
<  330 : Movie | rating : 8.35e+2 > 
<  331 : Movie | rating : 8.36e+2 > 
<  332 : Movie | rating : 8.37e+2 > 
<  333 : Movie | rating : 8.38e+2 > 
<  334 : Movie | rating : 8.39e+2 > 
<  335 : Actor | name : "a835",movies : (330, 331) > 
<  336 : Actor | name : "a836",movies : (330, 331, 332) > 
<  337 : Actress | name : "a837",movies : (331, 332, 333) > 
<  338 : Actress | name : "a838",movies : (332, 333, 334) > 
<  339 : Actress | name : "a839",movies : (333, 334) > 
<  340 : Movie | rating : 8.2e+2 > 
<  341 : Movie | rating : 8.21e+2 > 
<  342 : Movie | rating : 8.22e+2 > 
<  343 : Movie | rating : 8.23e+2 > 
<  344 : Movie | rating : 8.24e+2 > 
<  345 : Actor | name : "a820",movies : (340, 341, 342, 343) > 
<  346 : Actor | name : "a821",movies : (340, 341, 342, 343) > 
<  347 : Actor | name : "a822",movies : (341, 342, 343) > 
<  348 : Actress | name : "a823",movies : (341, 342, 343, 344) > 
<  349 : Actress | name : "a824",movies : (341, 342, 343, 344) > 
<  350 : Movie | rating : 8.25e+2 > 
<  351 : Movie | rating : 8.26e+2 > 
<  352 : Movie | rating : 8.27e+2 > 
<  353 : Movie | rating : 8.28e+2 > 
<  354 : Movie | rating : 8.29e+2 > 
<  355 : Actor | name : "a825",movies : (350, 351) > 
<  356 : Actor | name : "a826",movies : (350, 351, 352) > 
<  357 : Actress | name : "a827",movies : (351, 352, 353) > 
<  358 : Actress | name : "a828",movies : (352, 353, 354) > 
<  359 : Actress | name : "a829",movies : (353, 354) > 
<  360 : Movie | rating : 8.1e+2 > 
<  361 : Movie | rating : 8.11e+2 > 
<  362 : Movie | rating : 8.12e+2 > 
<  363 : Movie | rating : 8.13e+2 > 
<  364 : Movie | rating : 8.14e+2 > 
<  365 : Actor | name : "a810",movies : (360, 361, 362, 363) > 
<  366 : Actor | name : "a811",movies : (360, 361, 362, 363) > 
<  367 : Actor | name : "a812",movies : (361, 362, 363) > 
<  368 : Actress | name : "a813",movies : (361, 362, 363, 364) > 
<  369 : Actress | name : "a814",movies : (361, 362, 363, 364) > 
<  370 : Movie | rating : 8.15e+2 > 
<  371 : Movie | rating : 8.16e+2 > 
<  372 : Movie | rating : 8.17e+2 > 
<  373 : Movie | rating : 8.18e+2 > 
<  374 : Movie | rating : 8.19e+2 > 
<  375 : Actor | name : "a815",movies : (370, 371) > 
<  376 : Actor | name : "a816",movies : (370, 371, 372) > 
<  377 : Actress | name : "a817",movies : (371, 372, 373) > 
<  378 : Actress | name : "a818",movies : (372, 373, 374) > 
<  379 : Actress | name : "a819",movies : (373, 374) > 
<  380 : Movie | rating : 8.0e+2 > 
<  381 : Movie | rating : 8.01e+2 > 
<  382 : Movie | rating : 8.02e+2 > 
<  383 : Movie | rating : 8.03e+2 > 
<  384 : Movie | rating : 8.04e+2 > 
<  385 : Actor | name : "a800",movies : (380, 381, 382, 383) > 
<  386 : Actor | name : "a801",movies : (380, 381, 382, 383) > 
<  387 : Actor | name : "a802",movies : (381, 382, 383) > 
<  388 : Actress | name : "a803",movies : (381, 382, 383, 384) > 
<  389 : Actress | name : "a804",movies : (381, 382, 383, 384) > 
<  390 : Movie | rating : 8.05e+2 > 
<  391 : Movie | rating : 8.06e+2 > 
<  392 : Movie | rating : 8.07e+2 > 
<  393 : Movie | rating : 8.08e+2 > 
<  394 : Movie | rating : 8.09e+2 > 
<  395 : Actor | name : "a805",movies : (390, 391) > 
<  396 : Actor | name : "a806",movies : (390, 391, 392) > 
<  397 : Actress | name : "a807",movies : (391, 392, 393) > 
<  398 : Actress | name : "a808",movies : (392, 393, 394) > 
<  399 : Actress | name : "a809",movies : (393, 394) > 
<  400 : Movie | rating : 7.9e+2 > 
<  401 : Movie | rating : 7.91e+2 > 
<  402 : Movie | rating : 7.92e+2 > 
<  403 : Movie | rating : 7.93e+2 > 
<  404 : Movie | rating : 7.94e+2 > 
<  405 : Actor | name : "a790",movies : (400, 401, 402, 403) > 
<  406 : Actor | name : "a791",movies : (400, 401, 402, 403) > 
<  407 : Actor | name : "a792",movies : (401, 402, 403) > 
<  408 : Actress | name : "a793",movies : (401, 402, 403, 404) > 
<  409 : Actress | name : "a794",movies : (401, 402, 403, 404) > 
<  410 : Movie | rating : 7.95e+2 > 
<  411 : Movie | rating : 7.96e+2 > 
<  412 : Movie | rating : 7.97e+2 > 
<  413 : Movie | rating : 7.98e+2 > 
<  414 : Movie | rating : 7.99e+2 > 
<  415 : Actor | name : "a795",movies : (410, 411) > 
<  416 : Actor | name : "a796",movies : (410, 411, 412) > 
<  417 : Actress | name : "a797",movies : (411, 412, 413) > 
<  418 : Actress | name : "a798",movies : (412, 413, 414) > 
<  419 : Actress | name : "a799",movies : (413, 414) > 
<  420 : Movie | rating : 7.8e+2 > 
<  421 : Movie | rating : 7.81e+2 > 
<  422 : Movie | rating : 7.82e+2 > 
<  423 : Movie | rating : 7.83e+2 > 
<  424 : Movie | rating : 7.84e+2 > 
<  425 : Actor | name : "a780",movies : (420, 421, 422, 423) > 
<  426 : Actor | name : "a781",movies : (420, 421, 422, 423) > 
<  427 : Actor | name : "a782",movies : (421, 422, 423) > 
<  428 : Actress | name : "a783",movies : (421, 422, 423, 424) > 
<  429 : Actress | name : "a784",movies : (421, 422, 423, 424) > 
<  430 : Movie | rating : 7.85e+2 > 
<  431 : Movie | rating : 7.86e+2 > 
<  432 : Movie | rating : 7.87e+2 > 
<  433 : Movie | rating : 7.88e+2 > 
<  434 : Movie | rating : 7.89e+2 > 
<  435 : Actor | name : "a785",movies : (430, 431) > 
<  436 : Actor | name : "a786",movies : (430, 431, 432) > 
<  437 : Actress | name : "a787",movies : (431, 432, 433) > 
<  438 : Actress | name : "a788",movies : (432, 433, 434) > 
<  439 : Actress | name : "a789",movies : (433, 434) > 
<  440 : Movie | rating : 7.7e+2 > 
<  441 : Movie | rating : 7.71e+2 > 
<  442 : Movie | rating : 7.72e+2 > 
<  443 : Movie | rating : 7.73e+2 > 
<  444 : Movie | rating : 7.74e+2 > 
<  445 : Actor | name : "a770",movies : (440, 441, 442, 443) > 
<  446 : Actor | name : "a771",movies : (440, 441, 442, 443) > 
<  447 : Actor | name : "a772",movies : (441, 442, 443) > 
<  448 : Actress | name : "a773",movies : (441, 442, 443, 444) > 
<  449 : Actress | name : "a774",movies : (441, 442, 443, 444) > 
<  450 : Movie | rating : 7.75e+2 > 
<  451 : Movie | rating : 7.76e+2 > 
<  452 : Movie | rating : 7.77e+2 > 
<  453 : Movie | rating : 7.78e+2 > 
<  454 : Movie | rating : 7.79e+2 > 
<  455 : Actor | name : "a775",movies : (450, 451) > 
<  456 : Actor | name : "a776",movies : (450, 451, 452) > 
<  457 : Actress | name : "a777",movies : (451, 452, 453) > 
<  458 : Actress | name : "a778",movies : (452, 453, 454) > 
<  459 : Actress | name : "a779",movies : (453, 454) > 
<  460 : Movie | rating : 7.6e+2 > 
<  461 : Movie | rating : 7.61e+2 > 
<  462 : Movie | rating : 7.62e+2 > 
<  463 : Movie | rating : 7.63e+2 > 
<  464 : Movie | rating : 7.64e+2 > 
<  465 : Actor | name : "a760",movies : (460, 461, 462, 463) > 
<  466 : Actor | name : "a761",movies : (460, 461, 462, 463) > 
<  467 : Actor | name : "a762",movies : (461, 462, 463) > 
<  468 : Actress | name : "a763",movies : (461, 462, 463, 464) > 
<  469 : Actress | name : "a764",movies : (461, 462, 463, 464) > 
<  470 : Movie | rating : 7.65e+2 > 
<  471 : Movie | rating : 7.66e+2 > 
<  472 : Movie | rating : 7.67e+2 > 
<  473 : Movie | rating : 7.68e+2 > 
<  474 : Movie | rating : 7.69e+2 > 
<  475 : Actor | name : "a765",movies : (470, 471) > 
<  476 : Actor | name : "a766",movies : (470, 471, 472) > 
<  477 : Actress | name : "a767",movies : (471, 472, 473) > 
<  478 : Actress | name : "a768",movies : (472, 473, 474) > 
<  479 : Actress | name : "a769",movies : (473, 474) > 
<  480 : Movie | rating : 7.5e+2 > 
<  481 : Movie | rating : 7.51e+2 > 
<  482 : Movie | rating : 7.52e+2 > 
<  483 : Movie | rating : 7.53e+2 > 
<  484 : Movie | rating : 7.54e+2 > 
<  485 : Actor | name : "a750",movies : (480, 481, 482, 483) > 
<  486 : Actor | name : "a751",movies : (480, 481, 482, 483) > 
<  487 : Actor | name : "a752",movies : (481, 482, 483) > 
<  488 : Actress | name : "a753",movies : (481, 482, 483, 484) > 
<  489 : Actress | name : "a754",movies : (481, 482, 483, 484) > 
<  490 : Movie | rating : 7.55e+2 > 
<  491 : Movie | rating : 7.56e+2 > 
<  492 : Movie | rating : 7.57e+2 > 
<  493 : Movie | rating : 7.58e+2 > 
<  494 : Movie | rating : 7.59e+2 > 
<  495 : Actor | name : "a755",movies : (490, 491) > 
<  496 : Actor | name : "a756",movies : (490, 491, 492) > 
<  497 : Actress | name : "a757",movies : (491, 492, 493) > 
<  498 : Actress | name : "a758",movies : (492, 493, 494) > 
<  499 : Actress | name : "a759",movies : (493, 494) > 
<  500 : Movie | rating : 7.4e+2 > 
<  501 : Movie | rating : 7.41e+2 > 
<  502 : Movie | rating : 7.42e+2 > 
<  503 : Movie | rating : 7.43e+2 > 
<  504 : Movie | rating : 7.44e+2 > 
<  505 : Actor | name : "a740",movies : (500, 501, 502, 503) > 
<  506 : Actor | name : "a741",movies : (500, 501, 502, 503) > 
<  507 : Actor | name : "a742",movies : (501, 502, 503) > 
<  508 : Actress | name : "a743",movies : (501, 502, 503, 504) > 
<  509 : Actress | name : "a744",movies : (501, 502, 503, 504) > 
<  510 : Movie | rating : 7.45e+2 > 
<  511 : Movie | rating : 7.46e+2 > 
<  512 : Movie | rating : 7.47e+2 > 
<  513 : Movie | rating : 7.48e+2 > 
<  514 : Movie | rating : 7.49e+2 > 
<  515 : Actor | name : "a745",movies : (510, 511) > 
<  516 : Actor | name : "a746",movies : (510, 511, 512) > 
<  517 : Actress | name : "a747",movies : (511, 512, 513) > 
<  518 : Actress | name : "a748",movies : (512, 513, 514) > 
<  519 : Actress | name : "a749",movies : (513, 514) > 
<  520 : Movie | rating : 7.3e+2 > 
<  521 : Movie | rating : 7.31e+2 > 
<  522 : Movie | rating : 7.32e+2 > 
<  523 : Movie | rating : 7.33e+2 > 
<  524 : Movie | rating : 7.34e+2 > 
<  525 : Actor | name : "a730",movies : (520, 521, 522, 523) > 
<  526 : Actor | name : "a731",movies : (520, 521, 522, 523) > 
<  527 : Actor | name : "a732",movies : (521, 522, 523) > 
<  528 : Actress | name : "a733",movies : (521, 522, 523, 524) > 
<  529 : Actress | name : "a734",movies : (521, 522, 523, 524) > 
<  530 : Movie | rating : 7.35e+2 > 
<  531 : Movie | rating : 7.36e+2 > 
<  532 : Movie | rating : 7.37e+2 > 
<  533 : Movie | rating : 7.38e+2 > 
<  534 : Movie | rating : 7.39e+2 > 
<  535 : Actor | name : "a735",movies : (530, 531) > 
<  536 : Actor | name : "a736",movies : (530, 531, 532) > 
<  537 : Actress | name : "a737",movies : (531, 532, 533) > 
<  538 : Actress | name : "a738",movies : (532, 533, 534) > 
<  539 : Actress | name : "a739",movies : (533, 534) > 
<  540 : Movie | rating : 7.2e+2 > 
<  541 : Movie | rating : 7.21e+2 > 
<  542 : Movie | rating : 7.22e+2 > 
<  543 : Movie | rating : 7.23e+2 > 
<  544 : Movie | rating : 7.24e+2 > 
<  545 : Actor | name : "a720",movies : (540, 541, 542, 543) > 
<  546 : Actor | name : "a721",movies : (540, 541, 542, 543) > 
<  547 : Actor | name : "a722",movies : (541, 542, 543) > 
<  548 : Actress | name : "a723",movies : (541, 542, 543, 544) > 
<  549 : Actress | name : "a724",movies : (541, 542, 543, 544) > 
<  550 : Movie | rating : 7.25e+2 > 
<  551 : Movie | rating : 7.26e+2 > 
<  552 : Movie | rating : 7.27e+2 > 
<  553 : Movie | rating : 7.28e+2 > 
<  554 : Movie | rating : 7.29e+2 > 
<  555 : Actor | name : "a725",movies : (550, 551) > 
<  556 : Actor | name : "a726",movies : (550, 551, 552) > 
<  557 : Actress | name : "a727",movies : (551, 552, 553) > 
<  558 : Actress | name : "a728",movies : (552, 553, 554) > 
<  559 : Actress | name : "a729",movies : (553, 554) > 
<  560 : Movie | rating : 7.1e+2 > 
<  561 : Movie | rating : 7.11e+2 > 
<  562 : Movie | rating : 7.12e+2 > 
<  563 : Movie | rating : 7.13e+2 > 
<  564 : Movie | rating : 7.14e+2 > 
<  565 : Actor | name : "a710",movies : (560, 561, 562, 563) > 
<  566 : Actor | name : "a711",movies : (560, 561, 562, 563) > 
<  567 : Actor | name : "a712",movies : (561, 562, 563) > 
<  568 : Actress | name : "a713",movies : (561, 562, 563, 564) > 
<  569 : Actress | name : "a714",movies : (561, 562, 563, 564) > 
<  570 : Movie | rating : 7.15e+2 > 
<  571 : Movie | rating : 7.16e+2 > 
<  572 : Movie | rating : 7.17e+2 > 
<  573 : Movie | rating : 7.18e+2 > 
<  574 : Movie | rating : 7.19e+2 > 
<  575 : Actor | name : "a715",movies : (570, 571) > 
<  576 : Actor | name : "a716",movies : (570, 571, 572) > 
<  577 : Actress | name : "a717",movies : (571, 572, 573) > 
<  578 : Actress | name : "a718",movies : (572, 573, 574) > 
<  579 : Actress | name : "a719",movies : (573, 574) > 
<  580 : Movie | rating : 7.0e+2 > 
<  581 : Movie | rating : 7.01e+2 > 
<  582 : Movie | rating : 7.02e+2 > 
<  583 : Movie | rating : 7.03e+2 > 
<  584 : Movie | rating : 7.04e+2 > 
<  585 : Actor | name : "a700",movies : (580, 581, 582, 583) > 
<  586 : Actor | name : "a701",movies : (580, 581, 582, 583) > 
<  587 : Actor | name : "a702",movies : (581, 582, 583) > 
<  588 : Actress | name : "a703",movies : (581, 582, 583, 584) > 
<  589 : Actress | name : "a704",movies : (581, 582, 583, 584) > 
<  590 : Movie | rating : 7.05e+2 > 
<  591 : Movie | rating : 7.06e+2 > 
<  592 : Movie | rating : 7.07e+2 > 
<  593 : Movie | rating : 7.08e+2 > 
<  594 : Movie | rating : 7.09e+2 > 
<  595 : Actor | name : "a705",movies : (590, 591) > 
<  596 : Actor | name : "a706",movies : (590, 591, 592) > 
<  597 : Actress | name : "a707",movies : (591, 592, 593) > 
<  598 : Actress | name : "a708",movies : (592, 593, 594) > 
<  599 : Actress | name : "a709",movies : (593, 594) > 
<  600 : Movie | rating : 6.9e+2 > 
<  601 : Movie | rating : 6.91e+2 > 
<  602 : Movie | rating : 6.92e+2 > 
<  603 : Movie | rating : 6.93e+2 > 
<  604 : Movie | rating : 6.94e+2 > 
<  605 : Actor | name : "a690",movies : (600, 601, 602, 603) > 
<  606 : Actor | name : "a691",movies : (600, 601, 602, 603) > 
<  607 : Actor | name : "a692",movies : (601, 602, 603) > 
<  608 : Actress | name : "a693",movies : (601, 602, 603, 604) > 
<  609 : Actress | name : "a694",movies : (601, 602, 603, 604) > 
<  610 : Movie | rating : 6.95e+2 > 
<  611 : Movie | rating : 6.96e+2 > 
<  612 : Movie | rating : 6.97e+2 > 
<  613 : Movie | rating : 6.98e+2 > 
<  614 : Movie | rating : 6.99e+2 > 
<  615 : Actor | name : "a695",movies : (610, 611) > 
<  616 : Actor | name : "a696",movies : (610, 611, 612) > 
<  617 : Actress | name : "a697",movies : (611, 612, 613) > 
<  618 : Actress | name : "a698",movies : (612, 613, 614) > 
<  619 : Actress | name : "a699",movies : (613, 614) > 
<  620 : Movie | rating : 6.8e+2 > 
<  621 : Movie | rating : 6.81e+2 > 
<  622 : Movie | rating : 6.82e+2 > 
<  623 : Movie | rating : 6.83e+2 > 
<  624 : Movie | rating : 6.84e+2 > 
<  625 : Actor | name : "a680",movies : (620, 621, 622, 623) > 
<  626 : Actor | name : "a681",movies : (620, 621, 622, 623) > 
<  627 : Actor | name : "a682",movies : (621, 622, 623) > 
<  628 : Actress | name : "a683",movies : (621, 622, 623, 624) > 
<  629 : Actress | name : "a684",movies : (621, 622, 623, 624) > 
<  630 : Movie | rating : 6.85e+2 > 
<  631 : Movie | rating : 6.86e+2 > 
<  632 : Movie | rating : 6.87e+2 > 
<  633 : Movie | rating : 6.88e+2 > 
<  634 : Movie | rating : 6.89e+2 > 
<  635 : Actor | name : "a685",movies : (630, 631) > 
<  636 : Actor | name : "a686",movies : (630, 631, 632) > 
<  637 : Actress | name : "a687",movies : (631, 632, 633) > 
<  638 : Actress | name : "a688",movies : (632, 633, 634) > 
<  639 : Actress | name : "a689",movies : (633, 634) > 
<  640 : Movie | rating : 6.7e+2 > 
<  641 : Movie | rating : 6.71e+2 > 
<  642 : Movie | rating : 6.72e+2 > 
<  643 : Movie | rating : 6.73e+2 > 
<  644 : Movie | rating : 6.74e+2 > 
<  645 : Actor | name : "a670",movies : (640, 641, 642, 643) > 
<  646 : Actor | name : "a671",movies : (640, 641, 642, 643) > 
<  647 : Actor | name : "a672",movies : (641, 642, 643) > 
<  648 : Actress | name : "a673",movies : (641, 642, 643, 644) > 
<  649 : Actress | name : "a674",movies : (641, 642, 643, 644) > 
<  650 : Movie | rating : 6.75e+2 > 
<  651 : Movie | rating : 6.76e+2 > 
<  652 : Movie | rating : 6.77e+2 > 
<  653 : Movie | rating : 6.78e+2 > 
<  654 : Movie | rating : 6.79e+2 > 
<  655 : Actor | name : "a675",movies : (650, 651) > 
<  656 : Actor | name : "a676",movies : (650, 651, 652) > 
<  657 : Actress | name : "a677",movies : (651, 652, 653) > 
<  658 : Actress | name : "a678",movies : (652, 653, 654) > 
<  659 : Actress | name : "a679",movies : (653, 654) > 
<  660 : Movie | rating : 6.6e+2 > 
<  661 : Movie | rating : 6.61e+2 > 
<  662 : Movie | rating : 6.62e+2 > 
<  663 : Movie | rating : 6.63e+2 > 
<  664 : Movie | rating : 6.64e+2 > 
<  665 : Actor | name : "a660",movies : (660, 661, 662, 663) > 
<  666 : Actor | name : "a661",movies : (660, 661, 662, 663) > 
<  667 : Actor | name : "a662",movies : (661, 662, 663) > 
<  668 : Actress | name : "a663",movies : (661, 662, 663, 664) > 
<  669 : Actress | name : "a664",movies : (661, 662, 663, 664) > 
<  670 : Movie | rating : 6.65e+2 > 
<  671 : Movie | rating : 6.66e+2 > 
<  672 : Movie | rating : 6.67e+2 > 
<  673 : Movie | rating : 6.68e+2 > 
<  674 : Movie | rating : 6.69e+2 > 
<  675 : Actor | name : "a665",movies : (670, 671) > 
<  676 : Actor | name : "a666",movies : (670, 671, 672) > 
<  677 : Actress | name : "a667",movies : (671, 672, 673) > 
<  678 : Actress | name : "a668",movies : (672, 673, 674) > 
<  679 : Actress | name : "a669",movies : (673, 674) > 
<  680 : Movie | rating : 6.5e+2 > 
<  681 : Movie | rating : 6.51e+2 > 
<  682 : Movie | rating : 6.52e+2 > 
<  683 : Movie | rating : 6.53e+2 > 
<  684 : Movie | rating : 6.54e+2 > 
<  685 : Actor | name : "a650",movies : (680, 681, 682, 683) > 
<  686 : Actor | name : "a651",movies : (680, 681, 682, 683) > 
<  687 : Actor | name : "a652",movies : (681, 682, 683) > 
<  688 : Actress | name : "a653",movies : (681, 682, 683, 684) > 
<  689 : Actress | name : "a654",movies : (681, 682, 683, 684) > 
<  690 : Movie | rating : 6.55e+2 > 
<  691 : Movie | rating : 6.56e+2 > 
<  692 : Movie | rating : 6.57e+2 > 
<  693 : Movie | rating : 6.58e+2 > 
<  694 : Movie | rating : 6.59e+2 > 
<  695 : Actor | name : "a655",movies : (690, 691) > 
<  696 : Actor | name : "a656",movies : (690, 691, 692) > 
<  697 : Actress | name : "a657",movies : (691, 692, 693) > 
<  698 : Actress | name : "a658",movies : (692, 693, 694) > 
<  699 : Actress | name : "a659",movies : (693, 694) > 
<  700 : Movie | rating : 6.4e+2 > 
<  701 : Movie | rating : 6.41e+2 > 
<  702 : Movie | rating : 6.42e+2 > 
<  703 : Movie | rating : 6.43e+2 > 
<  704 : Movie | rating : 6.44e+2 > 
<  705 : Actor | name : "a640",movies : (700, 701, 702, 703) > 
<  706 : Actor | name : "a641",movies : (700, 701, 702, 703) > 
<  707 : Actor | name : "a642",movies : (701, 702, 703) > 
<  708 : Actress | name : "a643",movies : (701, 702, 703, 704) > 
<  709 : Actress | name : "a644",movies : (701, 702, 703, 704) > 
<  710 : Movie | rating : 6.45e+2 > 
<  711 : Movie | rating : 6.46e+2 > 
<  712 : Movie | rating : 6.47e+2 > 
<  713 : Movie | rating : 6.48e+2 > 
<  714 : Movie | rating : 6.49e+2 > 
<  715 : Actor | name : "a645",movies : (710, 711) > 
<  716 : Actor | name : "a646",movies : (710, 711, 712) > 
<  717 : Actress | name : "a647",movies : (711, 712, 713) > 
<  718 : Actress | name : "a648",movies : (712, 713, 714) > 
<  719 : Actress | name : "a649",movies : (713, 714) > 
<  720 : Movie | rating : 6.3e+2 > 
<  721 : Movie | rating : 6.31e+2 > 
<  722 : Movie | rating : 6.32e+2 > 
<  723 : Movie | rating : 6.33e+2 > 
<  724 : Movie | rating : 6.34e+2 > 
<  725 : Actor | name : "a630",movies : (720, 721, 722, 723) > 
<  726 : Actor | name : "a631",movies : (720, 721, 722, 723) > 
<  727 : Actor | name : "a632",movies : (721, 722, 723) > 
<  728 : Actress | name : "a633",movies : (721, 722, 723, 724) > 
<  729 : Actress | name : "a634",movies : (721, 722, 723, 724) > 
<  730 : Movie | rating : 6.35e+2 > 
<  731 : Movie | rating : 6.36e+2 > 
<  732 : Movie | rating : 6.37e+2 > 
<  733 : Movie | rating : 6.38e+2 > 
<  734 : Movie | rating : 6.39e+2 > 
<  735 : Actor | name : "a635",movies : (730, 731) > 
<  736 : Actor | name : "a636",movies : (730, 731, 732) > 
<  737 : Actress | name : "a637",movies : (731, 732, 733) > 
<  738 : Actress | name : "a638",movies : (732, 733, 734) > 
<  739 : Actress | name : "a639",movies : (733, 734) > 
<  740 : Movie | rating : 6.2e+2 > 
<  741 : Movie | rating : 6.21e+2 > 
<  742 : Movie | rating : 6.22e+2 > 
<  743 : Movie | rating : 6.23e+2 > 
<  744 : Movie | rating : 6.24e+2 > 
<  745 : Actor | name : "a620",movies : (740, 741, 742, 743) > 
<  746 : Actor | name : "a621",movies : (740, 741, 742, 743) > 
<  747 : Actor | name : "a622",movies : (741, 742, 743) > 
<  748 : Actress | name : "a623",movies : (741, 742, 743, 744) > 
<  749 : Actress | name : "a624",movies : (741, 742, 743, 744) > 
<  750 : Movie | rating : 6.25e+2 > 
<  751 : Movie | rating : 6.26e+2 > 
<  752 : Movie | rating : 6.27e+2 > 
<  753 : Movie | rating : 6.28e+2 > 
<  754 : Movie | rating : 6.29e+2 > 
<  755 : Actor | name : "a625",movies : (750, 751) > 
<  756 : Actor | name : "a626",movies : (750, 751, 752) > 
<  757 : Actress | name : "a627",movies : (751, 752, 753) > 
<  758 : Actress | name : "a628",movies : (752, 753, 754) > 
<  759 : Actress | name : "a629",movies : (753, 754) > 
<  760 : Movie | rating : 6.1e+2 > 
<  761 : Movie | rating : 6.11e+2 > 
<  762 : Movie | rating : 6.12e+2 > 
<  763 : Movie | rating : 6.13e+2 > 
<  764 : Movie | rating : 6.14e+2 > 
<  765 : Actor | name : "a610",movies : (760, 761, 762, 763) > 
<  766 : Actor | name : "a611",movies : (760, 761, 762, 763) > 
<  767 : Actor | name : "a612",movies : (761, 762, 763) > 
<  768 : Actress | name : "a613",movies : (761, 762, 763, 764) > 
<  769 : Actress | name : "a614",movies : (761, 762, 763, 764) > 
<  770 : Movie | rating : 6.15e+2 > 
<  771 : Movie | rating : 6.16e+2 > 
<  772 : Movie | rating : 6.17e+2 > 
<  773 : Movie | rating : 6.18e+2 > 
<  774 : Movie | rating : 6.19e+2 > 
<  775 : Actor | name : "a615",movies : (770, 771) > 
<  776 : Actor | name : "a616",movies : (770, 771, 772) > 
<  777 : Actress | name : "a617",movies : (771, 772, 773) > 
<  778 : Actress | name : "a618",movies : (772, 773, 774) > 
<  779 : Actress | name : "a619",movies : (773, 774) > 
<  780 : Movie | rating : 6.0e+2 > 
<  781 : Movie | rating : 6.01e+2 > 
<  782 : Movie | rating : 6.02e+2 > 
<  783 : Movie | rating : 6.03e+2 > 
<  784 : Movie | rating : 6.04e+2 > 
<  785 : Actor | name : "a600",movies : (780, 781, 782, 783) > 
<  786 : Actor | name : "a601",movies : (780, 781, 782, 783) > 
<  787 : Actor | name : "a602",movies : (781, 782, 783) > 
<  788 : Actress | name : "a603",movies : (781, 782, 783, 784) > 
<  789 : Actress | name : "a604",movies : (781, 782, 783, 784) > 
<  790 : Movie | rating : 6.05e+2 > 
<  791 : Movie | rating : 6.06e+2 > 
<  792 : Movie | rating : 6.07e+2 > 
<  793 : Movie | rating : 6.08e+2 > 
<  794 : Movie | rating : 6.09e+2 > 
<  795 : Actor | name : "a605",movies : (790, 791) > 
<  796 : Actor | name : "a606",movies : (790, 791, 792) > 
<  797 : Actress | name : "a607",movies : (791, 792, 793) > 
<  798 : Actress | name : "a608",movies : (792, 793, 794) > 
<  799 : Actress | name : "a609",movies : (793, 794) > 
<  800 : Movie | rating : 5.9e+2 > 
<  801 : Movie | rating : 5.91e+2 > 
<  802 : Movie | rating : 5.92e+2 > 
<  803 : Movie | rating : 5.93e+2 > 
<  804 : Movie | rating : 5.94e+2 > 
<  805 : Actor | name : "a590",movies : (800, 801, 802, 803) > 
<  806 : Actor | name : "a591",movies : (800, 801, 802, 803) > 
<  807 : Actor | name : "a592",movies : (801, 802, 803) > 
<  808 : Actress | name : "a593",movies : (801, 802, 803, 804) > 
<  809 : Actress | name : "a594",movies : (801, 802, 803, 804) > 
<  810 : Movie | rating : 5.95e+2 > 
<  811 : Movie | rating : 5.96e+2 > 
<  812 : Movie | rating : 5.97e+2 > 
<  813 : Movie | rating : 5.98e+2 > 
<  814 : Movie | rating : 5.99e+2 > 
<  815 : Actor | name : "a595",movies : (810, 811) > 
<  816 : Actor | name : "a596",movies : (810, 811, 812) > 
<  817 : Actress | name : "a597",movies : (811, 812, 813) > 
<  818 : Actress | name : "a598",movies : (812, 813, 814) > 
<  819 : Actress | name : "a599",movies : (813, 814) > 
<  820 : Movie | rating : 5.8e+2 > 
<  821 : Movie | rating : 5.81e+2 > 
<  822 : Movie | rating : 5.82e+2 > 
<  823 : Movie | rating : 5.83e+2 > 
<  824 : Movie | rating : 5.84e+2 > 
<  825 : Actor | name : "a580",movies : (820, 821, 822, 823) > 
<  826 : Actor | name : "a581",movies : (820, 821, 822, 823) > 
<  827 : Actor | name : "a582",movies : (821, 822, 823) > 
<  828 : Actress | name : "a583",movies : (821, 822, 823, 824) > 
<  829 : Actress | name : "a584",movies : (821, 822, 823, 824) > 
<  830 : Movie | rating : 5.85e+2 > 
<  831 : Movie | rating : 5.86e+2 > 
<  832 : Movie | rating : 5.87e+2 > 
<  833 : Movie | rating : 5.88e+2 > 
<  834 : Movie | rating : 5.89e+2 > 
<  835 : Actor | name : "a585",movies : (830, 831) > 
<  836 : Actor | name : "a586",movies : (830, 831, 832) > 
<  837 : Actress | name : "a587",movies : (831, 832, 833) > 
<  838 : Actress | name : "a588",movies : (832, 833, 834) > 
<  839 : Actress | name : "a589",movies : (833, 834) > 
<  840 : Movie | rating : 5.7e+2 > 
<  841 : Movie | rating : 5.71e+2 > 
<  842 : Movie | rating : 5.72e+2 > 
<  843 : Movie | rating : 5.73e+2 > 
<  844 : Movie | rating : 5.74e+2 > 
<  845 : Actor | name : "a570",movies : (840, 841, 842, 843) > 
<  846 : Actor | name : "a571",movies : (840, 841, 842, 843) > 
<  847 : Actor | name : "a572",movies : (841, 842, 843) > 
<  848 : Actress | name : "a573",movies : (841, 842, 843, 844) > 
<  849 : Actress | name : "a574",movies : (841, 842, 843, 844) > 
<  850 : Movie | rating : 5.75e+2 > 
<  851 : Movie | rating : 5.76e+2 > 
<  852 : Movie | rating : 5.77e+2 > 
<  853 : Movie | rating : 5.78e+2 > 
<  854 : Movie | rating : 5.79e+2 > 
<  855 : Actor | name : "a575",movies : (850, 851) > 
<  856 : Actor | name : "a576",movies : (850, 851, 852) > 
<  857 : Actress | name : "a577",movies : (851, 852, 853) > 
<  858 : Actress | name : "a578",movies : (852, 853, 854) > 
<  859 : Actress | name : "a579",movies : (853, 854) > 
<  860 : Movie | rating : 5.6e+2 > 
<  861 : Movie | rating : 5.61e+2 > 
<  862 : Movie | rating : 5.62e+2 > 
<  863 : Movie | rating : 5.63e+2 > 
<  864 : Movie | rating : 5.64e+2 > 
<  865 : Actor | name : "a560",movies : (860, 861, 862, 863) > 
<  866 : Actor | name : "a561",movies : (860, 861, 862, 863) > 
<  867 : Actor | name : "a562",movies : (861, 862, 863) > 
<  868 : Actress | name : "a563",movies : (861, 862, 863, 864) > 
<  869 : Actress | name : "a564",movies : (861, 862, 863, 864) > 
<  870 : Movie | rating : 5.65e+2 > 
<  871 : Movie | rating : 5.66e+2 > 
<  872 : Movie | rating : 5.67e+2 > 
<  873 : Movie | rating : 5.68e+2 > 
<  874 : Movie | rating : 5.69e+2 > 
<  875 : Actor | name : "a565",movies : (870, 871) > 
<  876 : Actor | name : "a566",movies : (870, 871, 872) > 
<  877 : Actress | name : "a567",movies : (871, 872, 873) > 
<  878 : Actress | name : "a568",movies : (872, 873, 874) > 
<  879 : Actress | name : "a569",movies : (873, 874) > 
<  880 : Movie | rating : 5.5e+2 > 
<  881 : Movie | rating : 5.51e+2 > 
<  882 : Movie | rating : 5.52e+2 > 
<  883 : Movie | rating : 5.53e+2 > 
<  884 : Movie | rating : 5.54e+2 > 
<  885 : Actor | name : "a550",movies : (880, 881, 882, 883) > 
<  886 : Actor | name : "a551",movies : (880, 881, 882, 883) > 
<  887 : Actor | name : "a552",movies : (881, 882, 883) > 
<  888 : Actress | name : "a553",movies : (881, 882, 883, 884) > 
<  889 : Actress | name : "a554",movies : (881, 882, 883, 884) > 
<  890 : Movie | rating : 5.55e+2 > 
<  891 : Movie | rating : 5.56e+2 > 
<  892 : Movie | rating : 5.57e+2 > 
<  893 : Movie | rating : 5.58e+2 > 
<  894 : Movie | rating : 5.59e+2 > 
<  895 : Actor | name : "a555",movies : (890, 891) > 
<  896 : Actor | name : "a556",movies : (890, 891, 892) > 
<  897 : Actress | name : "a557",movies : (891, 892, 893) > 
<  898 : Actress | name : "a558",movies : (892, 893, 894) > 
<  899 : Actress | name : "a559",movies : (893, 894) > 
<  900 : Movie | rating : 5.4e+2 > 
<  901 : Movie | rating : 5.41e+2 > 
<  902 : Movie | rating : 5.42e+2 > 
<  903 : Movie | rating : 5.43e+2 > 
<  904 : Movie | rating : 5.44e+2 > 
<  905 : Actor | name : "a540",movies : (900, 901, 902, 903) > 
<  906 : Actor | name : "a541",movies : (900, 901, 902, 903) > 
<  907 : Actor | name : "a542",movies : (901, 902, 903) > 
<  908 : Actress | name : "a543",movies : (901, 902, 903, 904) > 
<  909 : Actress | name : "a544",movies : (901, 902, 903, 904) > 
<  910 : Movie | rating : 5.45e+2 > 
<  911 : Movie | rating : 5.46e+2 > 
<  912 : Movie | rating : 5.47e+2 > 
<  913 : Movie | rating : 5.48e+2 > 
<  914 : Movie | rating : 5.49e+2 > 
<  915 : Actor | name : "a545",movies : (910, 911) > 
<  916 : Actor | name : "a546",movies : (910, 911, 912) > 
<  917 : Actress | name : "a547",movies : (911, 912, 913) > 
<  918 : Actress | name : "a548",movies : (912, 913, 914) > 
<  919 : Actress | name : "a549",movies : (913, 914) > 
<  920 : Movie | rating : 5.3e+2 > 
<  921 : Movie | rating : 5.31e+2 > 
<  922 : Movie | rating : 5.32e+2 > 
<  923 : Movie | rating : 5.33e+2 > 
<  924 : Movie | rating : 5.34e+2 > 
<  925 : Actor | name : "a530",movies : (920, 921, 922, 923) > 
<  926 : Actor | name : "a531",movies : (920, 921, 922, 923) > 
<  927 : Actor | name : "a532",movies : (921, 922, 923) > 
<  928 : Actress | name : "a533",movies : (921, 922, 923, 924) > 
<  929 : Actress | name : "a534",movies : (921, 922, 923, 924) > 
<  930 : Movie | rating : 5.35e+2 > 
<  931 : Movie | rating : 5.36e+2 > 
<  932 : Movie | rating : 5.37e+2 > 
<  933 : Movie | rating : 5.38e+2 > 
<  934 : Movie | rating : 5.39e+2 > 
<  935 : Actor | name : "a535",movies : (930, 931) > 
<  936 : Actor | name : "a536",movies : (930, 931, 932) > 
<  937 : Actress | name : "a537",movies : (931, 932, 933) > 
<  938 : Actress | name : "a538",movies : (932, 933, 934) > 
<  939 : Actress | name : "a539",movies : (933, 934) > 
<  940 : Movie | rating : 5.2e+2 > 
<  941 : Movie | rating : 5.21e+2 > 
<  942 : Movie | rating : 5.22e+2 > 
<  943 : Movie | rating : 5.23e+2 > 
<  944 : Movie | rating : 5.24e+2 > 
<  945 : Actor | name : "a520",movies : (940, 941, 942, 943) > 
<  946 : Actor | name : "a521",movies : (940, 941, 942, 943) > 
<  947 : Actor | name : "a522",movies : (941, 942, 943) > 
<  948 : Actress | name : "a523",movies : (941, 942, 943, 944) > 
<  949 : Actress | name : "a524",movies : (941, 942, 943, 944) > 
<  950 : Movie | rating : 5.25e+2 > 
<  951 : Movie | rating : 5.26e+2 > 
<  952 : Movie | rating : 5.27e+2 > 
<  953 : Movie | rating : 5.28e+2 > 
<  954 : Movie | rating : 5.29e+2 > 
<  955 : Actor | name : "a525",movies : (950, 951) > 
<  956 : Actor | name : "a526",movies : (950, 951, 952) > 
<  957 : Actress | name : "a527",movies : (951, 952, 953) > 
<  958 : Actress | name : "a528",movies : (952, 953, 954) > 
<  959 : Actress | name : "a529",movies : (953, 954) > 
<  960 : Movie | rating : 5.1e+2 > 
<  961 : Movie | rating : 5.11e+2 > 
<  962 : Movie | rating : 5.12e+2 > 
<  963 : Movie | rating : 5.13e+2 > 
<  964 : Movie | rating : 5.14e+2 > 
<  965 : Actor | name : "a510",movies : (960, 961, 962, 963) > 
<  966 : Actor | name : "a511",movies : (960, 961, 962, 963) > 
<  967 : Actor | name : "a512",movies : (961, 962, 963) > 
<  968 : Actress | name : "a513",movies : (961, 962, 963, 964) > 
<  969 : Actress | name : "a514",movies : (961, 962, 963, 964) > 
<  970 : Movie | rating : 5.15e+2 > 
<  971 : Movie | rating : 5.16e+2 > 
<  972 : Movie | rating : 5.17e+2 > 
<  973 : Movie | rating : 5.18e+2 > 
<  974 : Movie | rating : 5.19e+2 > 
<  975 : Actor | name : "a515",movies : (970, 971) > 
<  976 : Actor | name : "a516",movies : (970, 971, 972) > 
<  977 : Actress | name : "a517",movies : (971, 972, 973) > 
<  978 : Actress | name : "a518",movies : (972, 973, 974) > 
<  979 : Actress | name : "a519",movies : (973, 974) > 
<  980 : Movie | rating : 5.0e+2 > 
<  981 : Movie | rating : 5.01e+2 > 
<  982 : Movie | rating : 5.02e+2 > 
<  983 : Movie | rating : 5.03e+2 > 
<  984 : Movie | rating : 5.04e+2 > 
<  985 : Actor | name : "a500",movies : (980, 981, 982, 983) > 
<  986 : Actor | name : "a501",movies : (980, 981, 982, 983) > 
<  987 : Actor | name : "a502",movies : (981, 982, 983) > 
<  988 : Actress | name : "a503",movies : (981, 982, 983, 984) > 
<  989 : Actress | name : "a504",movies : (981, 982, 983, 984) > 
<  990 : Movie | rating : 5.05e+2 > 
<  991 : Movie | rating : 5.06e+2 > 
<  992 : Movie | rating : 5.07e+2 > 
<  993 : Movie | rating : 5.08e+2 > 
<  994 : Movie | rating : 5.09e+2 > 
<  995 : Actor | name : "a505",movies : (990, 991) > 
<  996 : Actor | name : "a506",movies : (990, 991, 992) > 
<  997 : Actress | name : "a507",movies : (991, 992, 993) > 
<  998 : Actress | name : "a508",movies : (992, 993, 994) > 
<  999 : Actress | name : "a509",movies : (993, 994) > 
<  1000 : Movie | rating : 4.9e+2 > 
<  1001 : Movie | rating : 4.91e+2 > 
<  1002 : Movie | rating : 4.92e+2 > 
<  1003 : Movie | rating : 4.93e+2 > 
<  1004 : Movie | rating : 4.94e+2 > 
<  1005 : Actor | name : "a490",movies : (1000, 1001, 1002, 1003) > 
<  1006 : Actor | name : "a491",movies : (1000, 1001, 1002, 1003) > 
<  1007 : Actor | name : "a492",movies : (1001, 1002, 1003) > 
<  1008 : Actress | name : "a493",movies : (1001, 1002, 1003, 1004) > 
<  1009 : Actress | name : "a494",movies : (1001, 1002, 1003, 1004) > 
<  1010 : Movie | rating : 4.95e+2 > 
<  1011 : Movie | rating : 4.96e+2 > 
<  1012 : Movie | rating : 4.97e+2 > 
<  1013 : Movie | rating : 4.98e+2 > 
<  1014 : Movie | rating : 4.99e+2 > 
<  1015 : Actor | name : "a495",movies : (1010, 1011) > 
<  1016 : Actor | name : "a496",movies : (1010, 1011, 1012) > 
<  1017 : Actress | name : "a497",movies : (1011, 1012, 1013) > 
<  1018 : Actress | name : "a498",movies : (1012, 1013, 1014) > 
<  1019 : Actress | name : "a499",movies : (1013, 1014) > 
<  1020 : Movie | rating : 4.8e+2 > 
<  1021 : Movie | rating : 4.81e+2 > 
<  1022 : Movie | rating : 4.82e+2 > 
<  1023 : Movie | rating : 4.83e+2 > 
<  1024 : Movie | rating : 4.84e+2 > 
<  1025 : Actor | name : "a480",movies : (1020, 1021, 1022, 1023) > 
<  1026 : Actor | name : "a481",movies : (1020, 1021, 1022, 1023) > 
<  1027 : Actor | name : "a482",movies : (1021, 1022, 1023) > 
<  1028 : Actress | name : "a483",movies : (1021, 1022, 1023, 1024) > 
<  1029 : Actress | name : "a484",movies : (1021, 1022, 1023, 1024) > 
<  1030 : Movie | rating : 4.85e+2 > 
<  1031 : Movie | rating : 4.86e+2 > 
<  1032 : Movie | rating : 4.87e+2 > 
<  1033 : Movie | rating : 4.88e+2 > 
<  1034 : Movie | rating : 4.89e+2 > 
<  1035 : Actor | name : "a485",movies : (1030, 1031) > 
<  1036 : Actor | name : "a486",movies : (1030, 1031, 1032) > 
<  1037 : Actress | name : "a487",movies : (1031, 1032, 1033) > 
<  1038 : Actress | name : "a488",movies : (1032, 1033, 1034) > 
<  1039 : Actress | name : "a489",movies : (1033, 1034) > 
<  1040 : Movie | rating : 4.7e+2 > 
<  1041 : Movie | rating : 4.71e+2 > 
<  1042 : Movie | rating : 4.72e+2 > 
<  1043 : Movie | rating : 4.73e+2 > 
<  1044 : Movie | rating : 4.74e+2 > 
<  1045 : Actor | name : "a470",movies : (1040, 1041, 1042, 1043) > 
<  1046 : Actor | name : "a471",movies : (1040, 1041, 1042, 1043) > 
<  1047 : Actor | name : "a472",movies : (1041, 1042, 1043) > 
<  1048 : Actress | name : "a473",movies : (1041, 1042, 1043, 1044) > 
<  1049 : Actress | name : "a474",movies : (1041, 1042, 1043, 1044) > 
<  1050 : Movie | rating : 4.75e+2 > 
<  1051 : Movie | rating : 4.76e+2 > 
<  1052 : Movie | rating : 4.77e+2 > 
<  1053 : Movie | rating : 4.78e+2 > 
<  1054 : Movie | rating : 4.79e+2 > 
<  1055 : Actor | name : "a475",movies : (1050, 1051) > 
<  1056 : Actor | name : "a476",movies : (1050, 1051, 1052) > 
<  1057 : Actress | name : "a477",movies : (1051, 1052, 1053) > 
<  1058 : Actress | name : "a478",movies : (1052, 1053, 1054) > 
<  1059 : Actress | name : "a479",movies : (1053, 1054) > 
<  1060 : Movie | rating : 4.6e+2 > 
<  1061 : Movie | rating : 4.61e+2 > 
<  1062 : Movie | rating : 4.62e+2 > 
<  1063 : Movie | rating : 4.63e+2 > 
<  1064 : Movie | rating : 4.64e+2 > 
<  1065 : Actor | name : "a460",movies : (1060, 1061, 1062, 1063) > 
<  1066 : Actor | name : "a461",movies : (1060, 1061, 1062, 1063) > 
<  1067 : Actor | name : "a462",movies : (1061, 1062, 1063) > 
<  1068 : Actress | name : "a463",movies : (1061, 1062, 1063, 1064) > 
<  1069 : Actress | name : "a464",movies : (1061, 1062, 1063, 1064) > 
<  1070 : Movie | rating : 4.65e+2 > 
<  1071 : Movie | rating : 4.66e+2 > 
<  1072 : Movie | rating : 4.67e+2 > 
<  1073 : Movie | rating : 4.68e+2 > 
<  1074 : Movie | rating : 4.69e+2 > 
<  1075 : Actor | name : "a465",movies : (1070, 1071) > 
<  1076 : Actor | name : "a466",movies : (1070, 1071, 1072) > 
<  1077 : Actress | name : "a467",movies : (1071, 1072, 1073) > 
<  1078 : Actress | name : "a468",movies : (1072, 1073, 1074) > 
<  1079 : Actress | name : "a469",movies : (1073, 1074) > 
<  1080 : Movie | rating : 4.5e+2 > 
<  1081 : Movie | rating : 4.51e+2 > 
<  1082 : Movie | rating : 4.52e+2 > 
<  1083 : Movie | rating : 4.53e+2 > 
<  1084 : Movie | rating : 4.54e+2 > 
<  1085 : Actor | name : "a450",movies : (1080, 1081, 1082, 1083) > 
<  1086 : Actor | name : "a451",movies : (1080, 1081, 1082, 1083) > 
<  1087 : Actor | name : "a452",movies : (1081, 1082, 1083) > 
<  1088 : Actress | name : "a453",movies : (1081, 1082, 1083, 1084) > 
<  1089 : Actress | name : "a454",movies : (1081, 1082, 1083, 1084) > 
<  1090 : Movie | rating : 4.55e+2 > 
<  1091 : Movie | rating : 4.56e+2 > 
<  1092 : Movie | rating : 4.57e+2 > 
<  1093 : Movie | rating : 4.58e+2 > 
<  1094 : Movie | rating : 4.59e+2 > 
<  1095 : Actor | name : "a455",movies : (1090, 1091) > 
<  1096 : Actor | name : "a456",movies : (1090, 1091, 1092) > 
<  1097 : Actress | name : "a457",movies : (1091, 1092, 1093) > 
<  1098 : Actress | name : "a458",movies : (1092, 1093, 1094) > 
<  1099 : Actress | name : "a459",movies : (1093, 1094) > 
<  1100 : Movie | rating : 4.4e+2 > 
<  1101 : Movie | rating : 4.41e+2 > 
<  1102 : Movie | rating : 4.42e+2 > 
<  1103 : Movie | rating : 4.43e+2 > 
<  1104 : Movie | rating : 4.44e+2 > 
<  1105 : Actor | name : "a440",movies : (1100, 1101, 1102, 1103) > 
<  1106 : Actor | name : "a441",movies : (1100, 1101, 1102, 1103) > 
<  1107 : Actor | name : "a442",movies : (1101, 1102, 1103) > 
<  1108 : Actress | name : "a443",movies : (1101, 1102, 1103, 1104) > 
<  1109 : Actress | name : "a444",movies : (1101, 1102, 1103, 1104) > 
<  1110 : Movie | rating : 4.45e+2 > 
<  1111 : Movie | rating : 4.46e+2 > 
<  1112 : Movie | rating : 4.47e+2 > 
<  1113 : Movie | rating : 4.48e+2 > 
<  1114 : Movie | rating : 4.49e+2 > 
<  1115 : Actor | name : "a445",movies : (1110, 1111) > 
<  1116 : Actor | name : "a446",movies : (1110, 1111, 1112) > 
<  1117 : Actress | name : "a447",movies : (1111, 1112, 1113) > 
<  1118 : Actress | name : "a448",movies : (1112, 1113, 1114) > 
<  1119 : Actress | name : "a449",movies : (1113, 1114) > 
<  1120 : Movie | rating : 4.3e+2 > 
<  1121 : Movie | rating : 4.31e+2 > 
<  1122 : Movie | rating : 4.32e+2 > 
<  1123 : Movie | rating : 4.33e+2 > 
<  1124 : Movie | rating : 4.34e+2 > 
<  1125 : Actor | name : "a430",movies : (1120, 1121, 1122, 1123) > 
<  1126 : Actor | name : "a431",movies : (1120, 1121, 1122, 1123) > 
<  1127 : Actor | name : "a432",movies : (1121, 1122, 1123) > 
<  1128 : Actress | name : "a433",movies : (1121, 1122, 1123, 1124) > 
<  1129 : Actress | name : "a434",movies : (1121, 1122, 1123, 1124) > 
<  1130 : Movie | rating : 4.35e+2 > 
<  1131 : Movie | rating : 4.36e+2 > 
<  1132 : Movie | rating : 4.37e+2 > 
<  1133 : Movie | rating : 4.38e+2 > 
<  1134 : Movie | rating : 4.39e+2 > 
<  1135 : Actor | name : "a435",movies : (1130, 1131) > 
<  1136 : Actor | name : "a436",movies : (1130, 1131, 1132) > 
<  1137 : Actress | name : "a437",movies : (1131, 1132, 1133) > 
<  1138 : Actress | name : "a438",movies : (1132, 1133, 1134) > 
<  1139 : Actress | name : "a439",movies : (1133, 1134) > 
<  1140 : Movie | rating : 4.2e+2 > 
<  1141 : Movie | rating : 4.21e+2 > 
<  1142 : Movie | rating : 4.22e+2 > 
<  1143 : Movie | rating : 4.23e+2 > 
<  1144 : Movie | rating : 4.24e+2 > 
<  1145 : Actor | name : "a420",movies : (1140, 1141, 1142, 1143) > 
<  1146 : Actor | name : "a421",movies : (1140, 1141, 1142, 1143) > 
<  1147 : Actor | name : "a422",movies : (1141, 1142, 1143) > 
<  1148 : Actress | name : "a423",movies : (1141, 1142, 1143, 1144) > 
<  1149 : Actress | name : "a424",movies : (1141, 1142, 1143, 1144) > 
<  1150 : Movie | rating : 4.25e+2 > 
<  1151 : Movie | rating : 4.26e+2 > 
<  1152 : Movie | rating : 4.27e+2 > 
<  1153 : Movie | rating : 4.28e+2 > 
<  1154 : Movie | rating : 4.29e+2 > 
<  1155 : Actor | name : "a425",movies : (1150, 1151) > 
<  1156 : Actor | name : "a426",movies : (1150, 1151, 1152) > 
<  1157 : Actress | name : "a427",movies : (1151, 1152, 1153) > 
<  1158 : Actress | name : "a428",movies : (1152, 1153, 1154) > 
<  1159 : Actress | name : "a429",movies : (1153, 1154) > 
<  1160 : Movie | rating : 4.1e+2 > 
<  1161 : Movie | rating : 4.11e+2 > 
<  1162 : Movie | rating : 4.12e+2 > 
<  1163 : Movie | rating : 4.13e+2 > 
<  1164 : Movie | rating : 4.14e+2 > 
<  1165 : Actor | name : "a410",movies : (1160, 1161, 1162, 1163) > 
<  1166 : Actor | name : "a411",movies : (1160, 1161, 1162, 1163) > 
<  1167 : Actor | name : "a412",movies : (1161, 1162, 1163) > 
<  1168 : Actress | name : "a413",movies : (1161, 1162, 1163, 1164) > 
<  1169 : Actress | name : "a414",movies : (1161, 1162, 1163, 1164) > 
<  1170 : Movie | rating : 4.15e+2 > 
<  1171 : Movie | rating : 4.16e+2 > 
<  1172 : Movie | rating : 4.17e+2 > 
<  1173 : Movie | rating : 4.18e+2 > 
<  1174 : Movie | rating : 4.19e+2 > 
<  1175 : Actor | name : "a415",movies : (1170, 1171) > 
<  1176 : Actor | name : "a416",movies : (1170, 1171, 1172) > 
<  1177 : Actress | name : "a417",movies : (1171, 1172, 1173) > 
<  1178 : Actress | name : "a418",movies : (1172, 1173, 1174) > 
<  1179 : Actress | name : "a419",movies : (1173, 1174) > 
<  1180 : Movie | rating : 4.0e+2 > 
<  1181 : Movie | rating : 4.01e+2 > 
<  1182 : Movie | rating : 4.02e+2 > 
<  1183 : Movie | rating : 4.03e+2 > 
<  1184 : Movie | rating : 4.04e+2 > 
<  1185 : Actor | name : "a400",movies : (1180, 1181, 1182, 1183) > 
<  1186 : Actor | name : "a401",movies : (1180, 1181, 1182, 1183) > 
<  1187 : Actor | name : "a402",movies : (1181, 1182, 1183) > 
<  1188 : Actress | name : "a403",movies : (1181, 1182, 1183, 1184) > 
<  1189 : Actress | name : "a404",movies : (1181, 1182, 1183, 1184) > 
<  1190 : Movie | rating : 4.05e+2 > 
<  1191 : Movie | rating : 4.06e+2 > 
<  1192 : Movie | rating : 4.07e+2 > 
<  1193 : Movie | rating : 4.08e+2 > 
<  1194 : Movie | rating : 4.09e+2 > 
<  1195 : Actor | name : "a405",movies : (1190, 1191) > 
<  1196 : Actor | name : "a406",movies : (1190, 1191, 1192) > 
<  1197 : Actress | name : "a407",movies : (1191, 1192, 1193) > 
<  1198 : Actress | name : "a408",movies : (1192, 1193, 1194) > 
<  1199 : Actress | name : "a409",movies : (1193, 1194) > 
<  1200 : Movie | rating : 3.9e+2 > 
<  1201 : Movie | rating : 3.91e+2 > 
<  1202 : Movie | rating : 3.92e+2 > 
<  1203 : Movie | rating : 3.93e+2 > 
<  1204 : Movie | rating : 3.94e+2 > 
<  1205 : Actor | name : "a390",movies : (1200, 1201, 1202, 1203) > 
<  1206 : Actor | name : "a391",movies : (1200, 1201, 1202, 1203) > 
<  1207 : Actor | name : "a392",movies : (1201, 1202, 1203) > 
<  1208 : Actress | name : "a393",movies : (1201, 1202, 1203, 1204) > 
<  1209 : Actress | name : "a394",movies : (1201, 1202, 1203, 1204) > 
<  1210 : Movie | rating : 3.95e+2 > 
<  1211 : Movie | rating : 3.96e+2 > 
<  1212 : Movie | rating : 3.97e+2 > 
<  1213 : Movie | rating : 3.98e+2 > 
<  1214 : Movie | rating : 3.99e+2 > 
<  1215 : Actor | name : "a395",movies : (1210, 1211) > 
<  1216 : Actor | name : "a396",movies : (1210, 1211, 1212) > 
<  1217 : Actress | name : "a397",movies : (1211, 1212, 1213) > 
<  1218 : Actress | name : "a398",movies : (1212, 1213, 1214) > 
<  1219 : Actress | name : "a399",movies : (1213, 1214) > 
<  1220 : Movie | rating : 3.8e+2 > 
<  1221 : Movie | rating : 3.81e+2 > 
<  1222 : Movie | rating : 3.82e+2 > 
<  1223 : Movie | rating : 3.83e+2 > 
<  1224 : Movie | rating : 3.84e+2 > 
<  1225 : Actor | name : "a380",movies : (1220, 1221, 1222, 1223) > 
<  1226 : Actor | name : "a381",movies : (1220, 1221, 1222, 1223) > 
<  1227 : Actor | name : "a382",movies : (1221, 1222, 1223) > 
<  1228 : Actress | name : "a383",movies : (1221, 1222, 1223, 1224) > 
<  1229 : Actress | name : "a384",movies : (1221, 1222, 1223, 1224) > 
<  1230 : Movie | rating : 3.85e+2 > 
<  1231 : Movie | rating : 3.86e+2 > 
<  1232 : Movie | rating : 3.87e+2 > 
<  1233 : Movie | rating : 3.88e+2 > 
<  1234 : Movie | rating : 3.89e+2 > 
<  1235 : Actor | name : "a385",movies : (1230, 1231) > 
<  1236 : Actor | name : "a386",movies : (1230, 1231, 1232) > 
<  1237 : Actress | name : "a387",movies : (1231, 1232, 1233) > 
<  1238 : Actress | name : "a388",movies : (1232, 1233, 1234) > 
<  1239 : Actress | name : "a389",movies : (1233, 1234) > 
<  1240 : Movie | rating : 3.7e+2 > 
<  1241 : Movie | rating : 3.71e+2 > 
<  1242 : Movie | rating : 3.72e+2 > 
<  1243 : Movie | rating : 3.73e+2 > 
<  1244 : Movie | rating : 3.74e+2 > 
<  1245 : Actor | name : "a370",movies : (1240, 1241, 1242, 1243) > 
<  1246 : Actor | name : "a371",movies : (1240, 1241, 1242, 1243) > 
<  1247 : Actor | name : "a372",movies : (1241, 1242, 1243) > 
<  1248 : Actress | name : "a373",movies : (1241, 1242, 1243, 1244) > 
<  1249 : Actress | name : "a374",movies : (1241, 1242, 1243, 1244) > 
<  1250 : Movie | rating : 3.75e+2 > 
<  1251 : Movie | rating : 3.76e+2 > 
<  1252 : Movie | rating : 3.77e+2 > 
<  1253 : Movie | rating : 3.78e+2 > 
<  1254 : Movie | rating : 3.79e+2 > 
<  1255 : Actor | name : "a375",movies : (1250, 1251) > 
<  1256 : Actor | name : "a376",movies : (1250, 1251, 1252) > 
<  1257 : Actress | name : "a377",movies : (1251, 1252, 1253) > 
<  1258 : Actress | name : "a378",movies : (1252, 1253, 1254) > 
<  1259 : Actress | name : "a379",movies : (1253, 1254) > 
<  1260 : Movie | rating : 3.6e+2 > 
<  1261 : Movie | rating : 3.61e+2 > 
<  1262 : Movie | rating : 3.62e+2 > 
<  1263 : Movie | rating : 3.63e+2 > 
<  1264 : Movie | rating : 3.64e+2 > 
<  1265 : Actor | name : "a360",movies : (1260, 1261, 1262, 1263) > 
<  1266 : Actor | name : "a361",movies : (1260, 1261, 1262, 1263) > 
<  1267 : Actor | name : "a362",movies : (1261, 1262, 1263) > 
<  1268 : Actress | name : "a363",movies : (1261, 1262, 1263, 1264) > 
<  1269 : Actress | name : "a364",movies : (1261, 1262, 1263, 1264) > 
<  1270 : Movie | rating : 3.65e+2 > 
<  1271 : Movie | rating : 3.66e+2 > 
<  1272 : Movie | rating : 3.67e+2 > 
<  1273 : Movie | rating : 3.68e+2 > 
<  1274 : Movie | rating : 3.69e+2 > 
<  1275 : Actor | name : "a365",movies : (1270, 1271) > 
<  1276 : Actor | name : "a366",movies : (1270, 1271, 1272) > 
<  1277 : Actress | name : "a367",movies : (1271, 1272, 1273) > 
<  1278 : Actress | name : "a368",movies : (1272, 1273, 1274) > 
<  1279 : Actress | name : "a369",movies : (1273, 1274) > 
<  1280 : Movie | rating : 3.5e+2 > 
<  1281 : Movie | rating : 3.51e+2 > 
<  1282 : Movie | rating : 3.52e+2 > 
<  1283 : Movie | rating : 3.53e+2 > 
<  1284 : Movie | rating : 3.54e+2 > 
<  1285 : Actor | name : "a350",movies : (1280, 1281, 1282, 1283) > 
<  1286 : Actor | name : "a351",movies : (1280, 1281, 1282, 1283) > 
<  1287 : Actor | name : "a352",movies : (1281, 1282, 1283) > 
<  1288 : Actress | name : "a353",movies : (1281, 1282, 1283, 1284) > 
<  1289 : Actress | name : "a354",movies : (1281, 1282, 1283, 1284) > 
<  1290 : Movie | rating : 3.55e+2 > 
<  1291 : Movie | rating : 3.56e+2 > 
<  1292 : Movie | rating : 3.57e+2 > 
<  1293 : Movie | rating : 3.58e+2 > 
<  1294 : Movie | rating : 3.59e+2 > 
<  1295 : Actor | name : "a355",movies : (1290, 1291) > 
<  1296 : Actor | name : "a356",movies : (1290, 1291, 1292) > 
<  1297 : Actress | name : "a357",movies : (1291, 1292, 1293) > 
<  1298 : Actress | name : "a358",movies : (1292, 1293, 1294) > 
<  1299 : Actress | name : "a359",movies : (1293, 1294) > 
<  1300 : Movie | rating : 3.4e+2 > 
<  1301 : Movie | rating : 3.41e+2 > 
<  1302 : Movie | rating : 3.42e+2 > 
<  1303 : Movie | rating : 3.43e+2 > 
<  1304 : Movie | rating : 3.44e+2 > 
<  1305 : Actor | name : "a340",movies : (1300, 1301, 1302, 1303) > 
<  1306 : Actor | name : "a341",movies : (1300, 1301, 1302, 1303) > 
<  1307 : Actor | name : "a342",movies : (1301, 1302, 1303) > 
<  1308 : Actress | name : "a343",movies : (1301, 1302, 1303, 1304) > 
<  1309 : Actress | name : "a344",movies : (1301, 1302, 1303, 1304) > 
<  1310 : Movie | rating : 3.45e+2 > 
<  1311 : Movie | rating : 3.46e+2 > 
<  1312 : Movie | rating : 3.47e+2 > 
<  1313 : Movie | rating : 3.48e+2 > 
<  1314 : Movie | rating : 3.49e+2 > 
<  1315 : Actor | name : "a345",movies : (1310, 1311) > 
<  1316 : Actor | name : "a346",movies : (1310, 1311, 1312) > 
<  1317 : Actress | name : "a347",movies : (1311, 1312, 1313) > 
<  1318 : Actress | name : "a348",movies : (1312, 1313, 1314) > 
<  1319 : Actress | name : "a349",movies : (1313, 1314) > 
<  1320 : Movie | rating : 3.3e+2 > 
<  1321 : Movie | rating : 3.31e+2 > 
<  1322 : Movie | rating : 3.32e+2 > 
<  1323 : Movie | rating : 3.33e+2 > 
<  1324 : Movie | rating : 3.34e+2 > 
<  1325 : Actor | name : "a330",movies : (1320, 1321, 1322, 1323) > 
<  1326 : Actor | name : "a331",movies : (1320, 1321, 1322, 1323) > 
<  1327 : Actor | name : "a332",movies : (1321, 1322, 1323) > 
<  1328 : Actress | name : "a333",movies : (1321, 1322, 1323, 1324) > 
<  1329 : Actress | name : "a334",movies : (1321, 1322, 1323, 1324) > 
<  1330 : Movie | rating : 3.35e+2 > 
<  1331 : Movie | rating : 3.36e+2 > 
<  1332 : Movie | rating : 3.37e+2 > 
<  1333 : Movie | rating : 3.38e+2 > 
<  1334 : Movie | rating : 3.39e+2 > 
<  1335 : Actor | name : "a335",movies : (1330, 1331) > 
<  1336 : Actor | name : "a336",movies : (1330, 1331, 1332) > 
<  1337 : Actress | name : "a337",movies : (1331, 1332, 1333) > 
<  1338 : Actress | name : "a338",movies : (1332, 1333, 1334) > 
<  1339 : Actress | name : "a339",movies : (1333, 1334) > 
<  1340 : Movie | rating : 3.2e+2 > 
<  1341 : Movie | rating : 3.21e+2 > 
<  1342 : Movie | rating : 3.22e+2 > 
<  1343 : Movie | rating : 3.23e+2 > 
<  1344 : Movie | rating : 3.24e+2 > 
<  1345 : Actor | name : "a320",movies : (1340, 1341, 1342, 1343) > 
<  1346 : Actor | name : "a321",movies : (1340, 1341, 1342, 1343) > 
<  1347 : Actor | name : "a322",movies : (1341, 1342, 1343) > 
<  1348 : Actress | name : "a323",movies : (1341, 1342, 1343, 1344) > 
<  1349 : Actress | name : "a324",movies : (1341, 1342, 1343, 1344) > 
<  1350 : Movie | rating : 3.25e+2 > 
<  1351 : Movie | rating : 3.26e+2 > 
<  1352 : Movie | rating : 3.27e+2 > 
<  1353 : Movie | rating : 3.28e+2 > 
<  1354 : Movie | rating : 3.29e+2 > 
<  1355 : Actor | name : "a325",movies : (1350, 1351) > 
<  1356 : Actor | name : "a326",movies : (1350, 1351, 1352) > 
<  1357 : Actress | name : "a327",movies : (1351, 1352, 1353) > 
<  1358 : Actress | name : "a328",movies : (1352, 1353, 1354) > 
<  1359 : Actress | name : "a329",movies : (1353, 1354) > 
<  1360 : Movie | rating : 3.1e+2 > 
<  1361 : Movie | rating : 3.11e+2 > 
<  1362 : Movie | rating : 3.12e+2 > 
<  1363 : Movie | rating : 3.13e+2 > 
<  1364 : Movie | rating : 3.14e+2 > 
<  1365 : Actor | name : "a310",movies : (1360, 1361, 1362, 1363) > 
<  1366 : Actor | name : "a311",movies : (1360, 1361, 1362, 1363) > 
<  1367 : Actor | name : "a312",movies : (1361, 1362, 1363) > 
<  1368 : Actress | name : "a313",movies : (1361, 1362, 1363, 1364) > 
<  1369 : Actress | name : "a314",movies : (1361, 1362, 1363, 1364) > 
<  1370 : Movie | rating : 3.15e+2 > 
<  1371 : Movie | rating : 3.16e+2 > 
<  1372 : Movie | rating : 3.17e+2 > 
<  1373 : Movie | rating : 3.18e+2 > 
<  1374 : Movie | rating : 3.19e+2 > 
<  1375 : Actor | name : "a315",movies : (1370, 1371) > 
<  1376 : Actor | name : "a316",movies : (1370, 1371, 1372) > 
<  1377 : Actress | name : "a317",movies : (1371, 1372, 1373) > 
<  1378 : Actress | name : "a318",movies : (1372, 1373, 1374) > 
<  1379 : Actress | name : "a319",movies : (1373, 1374) > 
<  1380 : Movie | rating : 3.0e+2 > 
<  1381 : Movie | rating : 3.01e+2 > 
<  1382 : Movie | rating : 3.02e+2 > 
<  1383 : Movie | rating : 3.03e+2 > 
<  1384 : Movie | rating : 3.04e+2 > 
<  1385 : Actor | name : "a300",movies : (1380, 1381, 1382, 1383) > 
<  1386 : Actor | name : "a301",movies : (1380, 1381, 1382, 1383) > 
<  1387 : Actor | name : "a302",movies : (1381, 1382, 1383) > 
<  1388 : Actress | name : "a303",movies : (1381, 1382, 1383, 1384) > 
<  1389 : Actress | name : "a304",movies : (1381, 1382, 1383, 1384) > 
<  1390 : Movie | rating : 3.05e+2 > 
<  1391 : Movie | rating : 3.06e+2 > 
<  1392 : Movie | rating : 3.07e+2 > 
<  1393 : Movie | rating : 3.08e+2 > 
<  1394 : Movie | rating : 3.09e+2 > 
<  1395 : Actor | name : "a305",movies : (1390, 1391) > 
<  1396 : Actor | name : "a306",movies : (1390, 1391, 1392) > 
<  1397 : Actress | name : "a307",movies : (1391, 1392, 1393) > 
<  1398 : Actress | name : "a308",movies : (1392, 1393, 1394) > 
<  1399 : Actress | name : "a309",movies : (1393, 1394) > 
<  1400 : Movie | rating : 2.9e+2 > 
<  1401 : Movie | rating : 2.91e+2 > 
<  1402 : Movie | rating : 2.92e+2 > 
<  1403 : Movie | rating : 2.93e+2 > 
<  1404 : Movie | rating : 2.94e+2 > 
<  1405 : Actor | name : "a290",movies : (1400, 1401, 1402, 1403) > 
<  1406 : Actor | name : "a291",movies : (1400, 1401, 1402, 1403) > 
<  1407 : Actor | name : "a292",movies : (1401, 1402, 1403) > 
<  1408 : Actress | name : "a293",movies : (1401, 1402, 1403, 1404) > 
<  1409 : Actress | name : "a294",movies : (1401, 1402, 1403, 1404) > 
<  1410 : Movie | rating : 2.95e+2 > 
<  1411 : Movie | rating : 2.96e+2 > 
<  1412 : Movie | rating : 2.97e+2 > 
<  1413 : Movie | rating : 2.98e+2 > 
<  1414 : Movie | rating : 2.99e+2 > 
<  1415 : Actor | name : "a295",movies : (1410, 1411) > 
<  1416 : Actor | name : "a296",movies : (1410, 1411, 1412) > 
<  1417 : Actress | name : "a297",movies : (1411, 1412, 1413) > 
<  1418 : Actress | name : "a298",movies : (1412, 1413, 1414) > 
<  1419 : Actress | name : "a299",movies : (1413, 1414) > 
<  1420 : Movie | rating : 2.8e+2 > 
<  1421 : Movie | rating : 2.81e+2 > 
<  1422 : Movie | rating : 2.82e+2 > 
<  1423 : Movie | rating : 2.83e+2 > 
<  1424 : Movie | rating : 2.84e+2 > 
<  1425 : Actor | name : "a280",movies : (1420, 1421, 1422, 1423) > 
<  1426 : Actor | name : "a281",movies : (1420, 1421, 1422, 1423) > 
<  1427 : Actor | name : "a282",movies : (1421, 1422, 1423) > 
<  1428 : Actress | name : "a283",movies : (1421, 1422, 1423, 1424) > 
<  1429 : Actress | name : "a284",movies : (1421, 1422, 1423, 1424) > 
<  1430 : Movie | rating : 2.85e+2 > 
<  1431 : Movie | rating : 2.86e+2 > 
<  1432 : Movie | rating : 2.87e+2 > 
<  1433 : Movie | rating : 2.88e+2 > 
<  1434 : Movie | rating : 2.89e+2 > 
<  1435 : Actor | name : "a285",movies : (1430, 1431) > 
<  1436 : Actor | name : "a286",movies : (1430, 1431, 1432) > 
<  1437 : Actress | name : "a287",movies : (1431, 1432, 1433) > 
<  1438 : Actress | name : "a288",movies : (1432, 1433, 1434) > 
<  1439 : Actress | name : "a289",movies : (1433, 1434) > 
<  1440 : Movie | rating : 2.7e+2 > 
<  1441 : Movie | rating : 2.71e+2 > 
<  1442 : Movie | rating : 2.72e+2 > 
<  1443 : Movie | rating : 2.73e+2 > 
<  1444 : Movie | rating : 2.74e+2 > 
<  1445 : Actor | name : "a270",movies : (1440, 1441, 1442, 1443) > 
<  1446 : Actor | name : "a271",movies : (1440, 1441, 1442, 1443) > 
<  1447 : Actor | name : "a272",movies : (1441, 1442, 1443) > 
<  1448 : Actress | name : "a273",movies : (1441, 1442, 1443, 1444) > 
<  1449 : Actress | name : "a274",movies : (1441, 1442, 1443, 1444) > 
<  1450 : Movie | rating : 2.75e+2 > 
<  1451 : Movie | rating : 2.76e+2 > 
<  1452 : Movie | rating : 2.77e+2 > 
<  1453 : Movie | rating : 2.78e+2 > 
<  1454 : Movie | rating : 2.79e+2 > 
<  1455 : Actor | name : "a275",movies : (1450, 1451) > 
<  1456 : Actor | name : "a276",movies : (1450, 1451, 1452) > 
<  1457 : Actress | name : "a277",movies : (1451, 1452, 1453) > 
<  1458 : Actress | name : "a278",movies : (1452, 1453, 1454) > 
<  1459 : Actress | name : "a279",movies : (1453, 1454) > 
<  1460 : Movie | rating : 2.6e+2 > 
<  1461 : Movie | rating : 2.61e+2 > 
<  1462 : Movie | rating : 2.62e+2 > 
<  1463 : Movie | rating : 2.63e+2 > 
<  1464 : Movie | rating : 2.64e+2 > 
<  1465 : Actor | name : "a260",movies : (1460, 1461, 1462, 1463) > 
<  1466 : Actor | name : "a261",movies : (1460, 1461, 1462, 1463) > 
<  1467 : Actor | name : "a262",movies : (1461, 1462, 1463) > 
<  1468 : Actress | name : "a263",movies : (1461, 1462, 1463, 1464) > 
<  1469 : Actress | name : "a264",movies : (1461, 1462, 1463, 1464) > 
<  1470 : Movie | rating : 2.65e+2 > 
<  1471 : Movie | rating : 2.66e+2 > 
<  1472 : Movie | rating : 2.67e+2 > 
<  1473 : Movie | rating : 2.68e+2 > 
<  1474 : Movie | rating : 2.69e+2 > 
<  1475 : Actor | name : "a265",movies : (1470, 1471) > 
<  1476 : Actor | name : "a266",movies : (1470, 1471, 1472) > 
<  1477 : Actress | name : "a267",movies : (1471, 1472, 1473) > 
<  1478 : Actress | name : "a268",movies : (1472, 1473, 1474) > 
<  1479 : Actress | name : "a269",movies : (1473, 1474) > 
<  1480 : Movie | rating : 2.5e+2 > 
<  1481 : Movie | rating : 2.51e+2 > 
<  1482 : Movie | rating : 2.52e+2 > 
<  1483 : Movie | rating : 2.53e+2 > 
<  1484 : Movie | rating : 2.54e+2 > 
<  1485 : Actor | name : "a250",movies : (1480, 1481, 1482, 1483) > 
<  1486 : Actor | name : "a251",movies : (1480, 1481, 1482, 1483) > 
<  1487 : Actor | name : "a252",movies : (1481, 1482, 1483) > 
<  1488 : Actress | name : "a253",movies : (1481, 1482, 1483, 1484) > 
<  1489 : Actress | name : "a254",movies : (1481, 1482, 1483, 1484) > 
<  1490 : Movie | rating : 2.55e+2 > 
<  1491 : Movie | rating : 2.56e+2 > 
<  1492 : Movie | rating : 2.57e+2 > 
<  1493 : Movie | rating : 2.58e+2 > 
<  1494 : Movie | rating : 2.59e+2 > 
<  1495 : Actor | name : "a255",movies : (1490, 1491) > 
<  1496 : Actor | name : "a256",movies : (1490, 1491, 1492) > 
<  1497 : Actress | name : "a257",movies : (1491, 1492, 1493) > 
<  1498 : Actress | name : "a258",movies : (1492, 1493, 1494) > 
<  1499 : Actress | name : "a259",movies : (1493, 1494) > 
<  1500 : Movie | rating : 2.4e+2 > 
<  1501 : Movie | rating : 2.41e+2 > 
<  1502 : Movie | rating : 2.42e+2 > 
<  1503 : Movie | rating : 2.43e+2 > 
<  1504 : Movie | rating : 2.44e+2 > 
<  1505 : Actor | name : "a240",movies : (1500, 1501, 1502, 1503) > 
<  1506 : Actor | name : "a241",movies : (1500, 1501, 1502, 1503) > 
<  1507 : Actor | name : "a242",movies : (1501, 1502, 1503) > 
<  1508 : Actress | name : "a243",movies : (1501, 1502, 1503, 1504) > 
<  1509 : Actress | name : "a244",movies : (1501, 1502, 1503, 1504) > 
<  1510 : Movie | rating : 2.45e+2 > 
<  1511 : Movie | rating : 2.46e+2 > 
<  1512 : Movie | rating : 2.47e+2 > 
<  1513 : Movie | rating : 2.48e+2 > 
<  1514 : Movie | rating : 2.49e+2 > 
<  1515 : Actor | name : "a245",movies : (1510, 1511) > 
<  1516 : Actor | name : "a246",movies : (1510, 1511, 1512) > 
<  1517 : Actress | name : "a247",movies : (1511, 1512, 1513) > 
<  1518 : Actress | name : "a248",movies : (1512, 1513, 1514) > 
<  1519 : Actress | name : "a249",movies : (1513, 1514) > 
<  1520 : Movie | rating : 2.3e+2 > 
<  1521 : Movie | rating : 2.31e+2 > 
<  1522 : Movie | rating : 2.32e+2 > 
<  1523 : Movie | rating : 2.33e+2 > 
<  1524 : Movie | rating : 2.34e+2 > 
<  1525 : Actor | name : "a230",movies : (1520, 1521, 1522, 1523) > 
<  1526 : Actor | name : "a231",movies : (1520, 1521, 1522, 1523) > 
<  1527 : Actor | name : "a232",movies : (1521, 1522, 1523) > 
<  1528 : Actress | name : "a233",movies : (1521, 1522, 1523, 1524) > 
<  1529 : Actress | name : "a234",movies : (1521, 1522, 1523, 1524) > 
<  1530 : Movie | rating : 2.35e+2 > 
<  1531 : Movie | rating : 2.36e+2 > 
<  1532 : Movie | rating : 2.37e+2 > 
<  1533 : Movie | rating : 2.38e+2 > 
<  1534 : Movie | rating : 2.39e+2 > 
<  1535 : Actor | name : "a235",movies : (1530, 1531) > 
<  1536 : Actor | name : "a236",movies : (1530, 1531, 1532) > 
<  1537 : Actress | name : "a237",movies : (1531, 1532, 1533) > 
<  1538 : Actress | name : "a238",movies : (1532, 1533, 1534) > 
<  1539 : Actress | name : "a239",movies : (1533, 1534) > 
<  1540 : Movie | rating : 2.2e+2 > 
<  1541 : Movie | rating : 2.21e+2 > 
<  1542 : Movie | rating : 2.22e+2 > 
<  1543 : Movie | rating : 2.23e+2 > 
<  1544 : Movie | rating : 2.24e+2 > 
<  1545 : Actor | name : "a220",movies : (1540, 1541, 1542, 1543) > 
<  1546 : Actor | name : "a221",movies : (1540, 1541, 1542, 1543) > 
<  1547 : Actor | name : "a222",movies : (1541, 1542, 1543) > 
<  1548 : Actress | name : "a223",movies : (1541, 1542, 1543, 1544) > 
<  1549 : Actress | name : "a224",movies : (1541, 1542, 1543, 1544) > 
<  1550 : Movie | rating : 2.25e+2 > 
<  1551 : Movie | rating : 2.26e+2 > 
<  1552 : Movie | rating : 2.27e+2 > 
<  1553 : Movie | rating : 2.28e+2 > 
<  1554 : Movie | rating : 2.29e+2 > 
<  1555 : Actor | name : "a225",movies : (1550, 1551) > 
<  1556 : Actor | name : "a226",movies : (1550, 1551, 1552) > 
<  1557 : Actress | name : "a227",movies : (1551, 1552, 1553) > 
<  1558 : Actress | name : "a228",movies : (1552, 1553, 1554) > 
<  1559 : Actress | name : "a229",movies : (1553, 1554) > 
<  1560 : Movie | rating : 2.1e+2 > 
<  1561 : Movie | rating : 2.11e+2 > 
<  1562 : Movie | rating : 2.12e+2 > 
<  1563 : Movie | rating : 2.13e+2 > 
<  1564 : Movie | rating : 2.14e+2 > 
<  1565 : Actor | name : "a210",movies : (1560, 1561, 1562, 1563) > 
<  1566 : Actor | name : "a211",movies : (1560, 1561, 1562, 1563) > 
<  1567 : Actor | name : "a212",movies : (1561, 1562, 1563) > 
<  1568 : Actress | name : "a213",movies : (1561, 1562, 1563, 1564) > 
<  1569 : Actress | name : "a214",movies : (1561, 1562, 1563, 1564) > 
<  1570 : Movie | rating : 2.15e+2 > 
<  1571 : Movie | rating : 2.16e+2 > 
<  1572 : Movie | rating : 2.17e+2 > 
<  1573 : Movie | rating : 2.18e+2 > 
<  1574 : Movie | rating : 2.19e+2 > 
<  1575 : Actor | name : "a215",movies : (1570, 1571) > 
<  1576 : Actor | name : "a216",movies : (1570, 1571, 1572) > 
<  1577 : Actress | name : "a217",movies : (1571, 1572, 1573) > 
<  1578 : Actress | name : "a218",movies : (1572, 1573, 1574) > 
<  1579 : Actress | name : "a219",movies : (1573, 1574) > 
<  1580 : Movie | rating : 2.0e+2 > 
<  1581 : Movie | rating : 2.01e+2 > 
<  1582 : Movie | rating : 2.02e+2 > 
<  1583 : Movie | rating : 2.03e+2 > 
<  1584 : Movie | rating : 2.04e+2 > 
<  1585 : Actor | name : "a200",movies : (1580, 1581, 1582, 1583) > 
<  1586 : Actor | name : "a201",movies : (1580, 1581, 1582, 1583) > 
<  1587 : Actor | name : "a202",movies : (1581, 1582, 1583) > 
<  1588 : Actress | name : "a203",movies : (1581, 1582, 1583, 1584) > 
<  1589 : Actress | name : "a204",movies : (1581, 1582, 1583, 1584) > 
<  1590 : Movie | rating : 2.05e+2 > 
<  1591 : Movie | rating : 2.06e+2 > 
<  1592 : Movie | rating : 2.07e+2 > 
<  1593 : Movie | rating : 2.08e+2 > 
<  1594 : Movie | rating : 2.09e+2 > 
<  1595 : Actor | name : "a205",movies : (1590, 1591) > 
<  1596 : Actor | name : "a206",movies : (1590, 1591, 1592) > 
<  1597 : Actress | name : "a207",movies : (1591, 1592, 1593) > 
<  1598 : Actress | name : "a208",movies : (1592, 1593, 1594) > 
<  1599 : Actress | name : "a209",movies : (1593, 1594) > 
<  1600 : Movie | rating : 1.9e+2 > 
<  1601 : Movie | rating : 1.91e+2 > 
<  1602 : Movie | rating : 1.92e+2 > 
<  1603 : Movie | rating : 1.93e+2 > 
<  1604 : Movie | rating : 1.94e+2 > 
<  1605 : Actor | name : "a190",movies : (1600, 1601, 1602, 1603) > 
<  1606 : Actor | name : "a191",movies : (1600, 1601, 1602, 1603) > 
<  1607 : Actor | name : "a192",movies : (1601, 1602, 1603) > 
<  1608 : Actress | name : "a193",movies : (1601, 1602, 1603, 1604) > 
<  1609 : Actress | name : "a194",movies : (1601, 1602, 1603, 1604) > 
<  1610 : Movie | rating : 1.95e+2 > 
<  1611 : Movie | rating : 1.96e+2 > 
<  1612 : Movie | rating : 1.97e+2 > 
<  1613 : Movie | rating : 1.98e+2 > 
<  1614 : Movie | rating : 1.99e+2 > 
<  1615 : Actor | name : "a195",movies : (1610, 1611) > 
<  1616 : Actor | name : "a196",movies : (1610, 1611, 1612) > 
<  1617 : Actress | name : "a197",movies : (1611, 1612, 1613) > 
<  1618 : Actress | name : "a198",movies : (1612, 1613, 1614) > 
<  1619 : Actress | name : "a199",movies : (1613, 1614) > 
<  1620 : Movie | rating : 1.8e+2 > 
<  1621 : Movie | rating : 1.81e+2 > 
<  1622 : Movie | rating : 1.82e+2 > 
<  1623 : Movie | rating : 1.83e+2 > 
<  1624 : Movie | rating : 1.84e+2 > 
<  1625 : Actor | name : "a180",movies : (1620, 1621, 1622, 1623) > 
<  1626 : Actor | name : "a181",movies : (1620, 1621, 1622, 1623) > 
<  1627 : Actor | name : "a182",movies : (1621, 1622, 1623) > 
<  1628 : Actress | name : "a183",movies : (1621, 1622, 1623, 1624) > 
<  1629 : Actress | name : "a184",movies : (1621, 1622, 1623, 1624) > 
<  1630 : Movie | rating : 1.85e+2 > 
<  1631 : Movie | rating : 1.86e+2 > 
<  1632 : Movie | rating : 1.87e+2 > 
<  1633 : Movie | rating : 1.88e+2 > 
<  1634 : Movie | rating : 1.89e+2 > 
<  1635 : Actor | name : "a185",movies : (1630, 1631) > 
<  1636 : Actor | name : "a186",movies : (1630, 1631, 1632) > 
<  1637 : Actress | name : "a187",movies : (1631, 1632, 1633) > 
<  1638 : Actress | name : "a188",movies : (1632, 1633, 1634) > 
<  1639 : Actress | name : "a189",movies : (1633, 1634) > 
<  1640 : Movie | rating : 1.7e+2 > 
<  1641 : Movie | rating : 1.71e+2 > 
<  1642 : Movie | rating : 1.72e+2 > 
<  1643 : Movie | rating : 1.73e+2 > 
<  1644 : Movie | rating : 1.74e+2 > 
<  1645 : Actor | name : "a170",movies : (1640, 1641, 1642, 1643) > 
<  1646 : Actor | name : "a171",movies : (1640, 1641, 1642, 1643) > 
<  1647 : Actor | name : "a172",movies : (1641, 1642, 1643) > 
<  1648 : Actress | name : "a173",movies : (1641, 1642, 1643, 1644) > 
<  1649 : Actress | name : "a174",movies : (1641, 1642, 1643, 1644) > 
<  1650 : Movie | rating : 1.75e+2 > 
<  1651 : Movie | rating : 1.76e+2 > 
<  1652 : Movie | rating : 1.77e+2 > 
<  1653 : Movie | rating : 1.78e+2 > 
<  1654 : Movie | rating : 1.79e+2 > 
<  1655 : Actor | name : "a175",movies : (1650, 1651) > 
<  1656 : Actor | name : "a176",movies : (1650, 1651, 1652) > 
<  1657 : Actress | name : "a177",movies : (1651, 1652, 1653) > 
<  1658 : Actress | name : "a178",movies : (1652, 1653, 1654) > 
<  1659 : Actress | name : "a179",movies : (1653, 1654) > 
<  1660 : Movie | rating : 1.6e+2 > 
<  1661 : Movie | rating : 1.61e+2 > 
<  1662 : Movie | rating : 1.62e+2 > 
<  1663 : Movie | rating : 1.63e+2 > 
<  1664 : Movie | rating : 1.64e+2 > 
<  1665 : Actor | name : "a160",movies : (1660, 1661, 1662, 1663) > 
<  1666 : Actor | name : "a161",movies : (1660, 1661, 1662, 1663) > 
<  1667 : Actor | name : "a162",movies : (1661, 1662, 1663) > 
<  1668 : Actress | name : "a163",movies : (1661, 1662, 1663, 1664) > 
<  1669 : Actress | name : "a164",movies : (1661, 1662, 1663, 1664) > 
<  1670 : Movie | rating : 1.65e+2 > 
<  1671 : Movie | rating : 1.66e+2 > 
<  1672 : Movie | rating : 1.67e+2 > 
<  1673 : Movie | rating : 1.68e+2 > 
<  1674 : Movie | rating : 1.69e+2 > 
<  1675 : Actor | name : "a165",movies : (1670, 1671) > 
<  1676 : Actor | name : "a166",movies : (1670, 1671, 1672) > 
<  1677 : Actress | name : "a167",movies : (1671, 1672, 1673) > 
<  1678 : Actress | name : "a168",movies : (1672, 1673, 1674) > 
<  1679 : Actress | name : "a169",movies : (1673, 1674) > 
<  1680 : Movie | rating : 1.5e+2 > 
<  1681 : Movie | rating : 1.51e+2 > 
<  1682 : Movie | rating : 1.52e+2 > 
<  1683 : Movie | rating : 1.53e+2 > 
<  1684 : Movie | rating : 1.54e+2 > 
<  1685 : Actor | name : "a150",movies : (1680, 1681, 1682, 1683) > 
<  1686 : Actor | name : "a151",movies : (1680, 1681, 1682, 1683) > 
<  1687 : Actor | name : "a152",movies : (1681, 1682, 1683) > 
<  1688 : Actress | name : "a153",movies : (1681, 1682, 1683, 1684) > 
<  1689 : Actress | name : "a154",movies : (1681, 1682, 1683, 1684) > 
<  1690 : Movie | rating : 1.55e+2 > 
<  1691 : Movie | rating : 1.56e+2 > 
<  1692 : Movie | rating : 1.57e+2 > 
<  1693 : Movie | rating : 1.58e+2 > 
<  1694 : Movie | rating : 1.59e+2 > 
<  1695 : Actor | name : "a155",movies : (1690, 1691) > 
<  1696 : Actor | name : "a156",movies : (1690, 1691, 1692) > 
<  1697 : Actress | name : "a157",movies : (1691, 1692, 1693) > 
<  1698 : Actress | name : "a158",movies : (1692, 1693, 1694) > 
<  1699 : Actress | name : "a159",movies : (1693, 1694) > 
<  1700 : Movie | rating : 1.4e+2 > 
<  1701 : Movie | rating : 1.41e+2 > 
<  1702 : Movie | rating : 1.42e+2 > 
<  1703 : Movie | rating : 1.43e+2 > 
<  1704 : Movie | rating : 1.44e+2 > 
<  1705 : Actor | name : "a140",movies : (1700, 1701, 1702, 1703) > 
<  1706 : Actor | name : "a141",movies : (1700, 1701, 1702, 1703) > 
<  1707 : Actor | name : "a142",movies : (1701, 1702, 1703) > 
<  1708 : Actress | name : "a143",movies : (1701, 1702, 1703, 1704) > 
<  1709 : Actress | name : "a144",movies : (1701, 1702, 1703, 1704) > 
<  1710 : Movie | rating : 1.45e+2 > 
<  1711 : Movie | rating : 1.46e+2 > 
<  1712 : Movie | rating : 1.47e+2 > 
<  1713 : Movie | rating : 1.48e+2 > 
<  1714 : Movie | rating : 1.49e+2 > 
<  1715 : Actor | name : "a145",movies : (1710, 1711) > 
<  1716 : Actor | name : "a146",movies : (1710, 1711, 1712) > 
<  1717 : Actress | name : "a147",movies : (1711, 1712, 1713) > 
<  1718 : Actress | name : "a148",movies : (1712, 1713, 1714) > 
<  1719 : Actress | name : "a149",movies : (1713, 1714) > 
<  1720 : Movie | rating : 1.3e+2 > 
<  1721 : Movie | rating : 1.31e+2 > 
<  1722 : Movie | rating : 1.32e+2 > 
<  1723 : Movie | rating : 1.33e+2 > 
<  1724 : Movie | rating : 1.34e+2 > 
<  1725 : Actor | name : "a130",movies : (1720, 1721, 1722, 1723) > 
<  1726 : Actor | name : "a131",movies : (1720, 1721, 1722, 1723) > 
<  1727 : Actor | name : "a132",movies : (1721, 1722, 1723) > 
<  1728 : Actress | name : "a133",movies : (1721, 1722, 1723, 1724) > 
<  1729 : Actress | name : "a134",movies : (1721, 1722, 1723, 1724) > 
<  1730 : Movie | rating : 1.35e+2 > 
<  1731 : Movie | rating : 1.36e+2 > 
<  1732 : Movie | rating : 1.37e+2 > 
<  1733 : Movie | rating : 1.38e+2 > 
<  1734 : Movie | rating : 1.39e+2 > 
<  1735 : Actor | name : "a135",movies : (1730, 1731) > 
<  1736 : Actor | name : "a136",movies : (1730, 1731, 1732) > 
<  1737 : Actress | name : "a137",movies : (1731, 1732, 1733) > 
<  1738 : Actress | name : "a138",movies : (1732, 1733, 1734) > 
<  1739 : Actress | name : "a139",movies : (1733, 1734) > 
<  1740 : Movie | rating : 1.2e+2 > 
<  1741 : Movie | rating : 1.21e+2 > 
<  1742 : Movie | rating : 1.22e+2 > 
<  1743 : Movie | rating : 1.23e+2 > 
<  1744 : Movie | rating : 1.24e+2 > 
<  1745 : Actor | name : "a120",movies : (1740, 1741, 1742, 1743) > 
<  1746 : Actor | name : "a121",movies : (1740, 1741, 1742, 1743) > 
<  1747 : Actor | name : "a122",movies : (1741, 1742, 1743) > 
<  1748 : Actress | name : "a123",movies : (1741, 1742, 1743, 1744) > 
<  1749 : Actress | name : "a124",movies : (1741, 1742, 1743, 1744) > 
<  1750 : Movie | rating : 1.25e+2 > 
<  1751 : Movie | rating : 1.26e+2 > 
<  1752 : Movie | rating : 1.27e+2 > 
<  1753 : Movie | rating : 1.28e+2 > 
<  1754 : Movie | rating : 1.29e+2 > 
<  1755 : Actor | name : "a125",movies : (1750, 1751) > 
<  1756 : Actor | name : "a126",movies : (1750, 1751, 1752) > 
<  1757 : Actress | name : "a127",movies : (1751, 1752, 1753) > 
<  1758 : Actress | name : "a128",movies : (1752, 1753, 1754) > 
<  1759 : Actress | name : "a129",movies : (1753, 1754) > 
<  1760 : Movie | rating : 1.1e+2 > 
<  1761 : Movie | rating : 1.11e+2 > 
<  1762 : Movie | rating : 1.12e+2 > 
<  1763 : Movie | rating : 1.13e+2 > 
<  1764 : Movie | rating : 1.14e+2 > 
<  1765 : Actor | name : "a110",movies : (1760, 1761, 1762, 1763) > 
<  1766 : Actor | name : "a111",movies : (1760, 1761, 1762, 1763) > 
<  1767 : Actor | name : "a112",movies : (1761, 1762, 1763) > 
<  1768 : Actress | name : "a113",movies : (1761, 1762, 1763, 1764) > 
<  1769 : Actress | name : "a114",movies : (1761, 1762, 1763, 1764) > 
<  1770 : Movie | rating : 1.15e+2 > 
<  1771 : Movie | rating : 1.16e+2 > 
<  1772 : Movie | rating : 1.17e+2 > 
<  1773 : Movie | rating : 1.18e+2 > 
<  1774 : Movie | rating : 1.19e+2 > 
<  1775 : Actor | name : "a115",movies : (1770, 1771) > 
<  1776 : Actor | name : "a116",movies : (1770, 1771, 1772) > 
<  1777 : Actress | name : "a117",movies : (1771, 1772, 1773) > 
<  1778 : Actress | name : "a118",movies : (1772, 1773, 1774) > 
<  1779 : Actress | name : "a119",movies : (1773, 1774) > 
<  1780 : Movie | rating : 1.0e+2 > 
<  1781 : Movie | rating : 1.01e+2 > 
<  1782 : Movie | rating : 1.02e+2 > 
<  1783 : Movie | rating : 1.03e+2 > 
<  1784 : Movie | rating : 1.04e+2 > 
<  1785 : Actor | name : "a100",movies : (1780, 1781, 1782, 1783) > 
<  1786 : Actor | name : "a101",movies : (1780, 1781, 1782, 1783) > 
<  1787 : Actor | name : "a102",movies : (1781, 1782, 1783) > 
<  1788 : Actress | name : "a103",movies : (1781, 1782, 1783, 1784) > 
<  1789 : Actress | name : "a104",movies : (1781, 1782, 1783, 1784) > 
<  1790 : Movie | rating : 1.05e+2 > 
<  1791 : Movie | rating : 1.06e+2 > 
<  1792 : Movie | rating : 1.07e+2 > 
<  1793 : Movie | rating : 1.08e+2 > 
<  1794 : Movie | rating : 1.09e+2 > 
<  1795 : Actor | name : "a105",movies : (1790, 1791) > 
<  1796 : Actor | name : "a106",movies : (1790, 1791, 1792) > 
<  1797 : Actress | name : "a107",movies : (1791, 1792, 1793) > 
<  1798 : Actress | name : "a108",movies : (1792, 1793, 1794) > 
<  1799 : Actress | name : "a109",movies : (1793, 1794) > 
<  1800 : Movie | rating : 9.0e+1 > 
<  1801 : Movie | rating : 9.1e+1 > 
<  1802 : Movie | rating : 9.2e+1 > 
<  1803 : Movie | rating : 9.3e+1 > 
<  1804 : Movie | rating : 9.4e+1 > 
<  1805 : Actor | name : "a90",movies : (1800, 1801, 1802, 1803) > 
<  1806 : Actor | name : "a91",movies : (1800, 1801, 1802, 1803) > 
<  1807 : Actor | name : "a92",movies : (1801, 1802, 1803) > 
<  1808 : Actress | name : "a93",movies : (1801, 1802, 1803, 1804) > 
<  1809 : Actress | name : "a94",movies : (1801, 1802, 1803, 1804) > 
<  1810 : Movie | rating : 9.5e+1 > 
<  1811 : Movie | rating : 9.6e+1 > 
<  1812 : Movie | rating : 9.7e+1 > 
<  1813 : Movie | rating : 9.8e+1 > 
<  1814 : Movie | rating : 9.9e+1 > 
<  1815 : Actor | name : "a95",movies : (1810, 1811) > 
<  1816 : Actor | name : "a96",movies : (1810, 1811, 1812) > 
<  1817 : Actress | name : "a97",movies : (1811, 1812, 1813) > 
<  1818 : Actress | name : "a98",movies : (1812, 1813, 1814) > 
<  1819 : Actress | name : "a99",movies : (1813, 1814) > 
<  1820 : Movie | rating : 8.0e+1 > 
<  1821 : Movie | rating : 8.1e+1 > 
<  1822 : Movie | rating : 8.2e+1 > 
<  1823 : Movie | rating : 8.3e+1 > 
<  1824 : Movie | rating : 8.4e+1 > 
<  1825 : Actor | name : "a80",movies : (1820, 1821, 1822, 1823) > 
<  1826 : Actor | name : "a81",movies : (1820, 1821, 1822, 1823) > 
<  1827 : Actor | name : "a82",movies : (1821, 1822, 1823) > 
<  1828 : Actress | name : "a83",movies : (1821, 1822, 1823, 1824) > 
<  1829 : Actress | name : "a84",movies : (1821, 1822, 1823, 1824) > 
<  1830 : Movie | rating : 8.5e+1 > 
<  1831 : Movie | rating : 8.6e+1 > 
<  1832 : Movie | rating : 8.7e+1 > 
<  1833 : Movie | rating : 8.8e+1 > 
<  1834 : Movie | rating : 8.9e+1 > 
<  1835 : Actor | name : "a85",movies : (1830, 1831) > 
<  1836 : Actor | name : "a86",movies : (1830, 1831, 1832) > 
<  1837 : Actress | name : "a87",movies : (1831, 1832, 1833) > 
<  1838 : Actress | name : "a88",movies : (1832, 1833, 1834) > 
<  1839 : Actress | name : "a89",movies : (1833, 1834) > 
<  1840 : Movie | rating : 7.0e+1 > 
<  1841 : Movie | rating : 7.1e+1 > 
<  1842 : Movie | rating : 7.2e+1 > 
<  1843 : Movie | rating : 7.3e+1 > 
<  1844 : Movie | rating : 7.4e+1 > 
<  1845 : Actor | name : "a70",movies : (1840, 1841, 1842, 1843) > 
<  1846 : Actor | name : "a71",movies : (1840, 1841, 1842, 1843) > 
<  1847 : Actor | name : "a72",movies : (1841, 1842, 1843) > 
<  1848 : Actress | name : "a73",movies : (1841, 1842, 1843, 1844) > 
<  1849 : Actress | name : "a74",movies : (1841, 1842, 1843, 1844) > 
<  1850 : Movie | rating : 7.5e+1 > 
<  1851 : Movie | rating : 7.6e+1 > 
<  1852 : Movie | rating : 7.7e+1 > 
<  1853 : Movie | rating : 7.8e+1 > 
<  1854 : Movie | rating : 7.9e+1 > 
<  1855 : Actor | name : "a75",movies : (1850, 1851) > 
<  1856 : Actor | name : "a76",movies : (1850, 1851, 1852) > 
<  1857 : Actress | name : "a77",movies : (1851, 1852, 1853) > 
<  1858 : Actress | name : "a78",movies : (1852, 1853, 1854) > 
<  1859 : Actress | name : "a79",movies : (1853, 1854) > 
<  1860 : Movie | rating : 6.0e+1 > 
<  1861 : Movie | rating : 6.1e+1 > 
<  1862 : Movie | rating : 6.2e+1 > 
<  1863 : Movie | rating : 6.3e+1 > 
<  1864 : Movie | rating : 6.4e+1 > 
<  1865 : Actor | name : "a60",movies : (1860, 1861, 1862, 1863) > 
<  1866 : Actor | name : "a61",movies : (1860, 1861, 1862, 1863) > 
<  1867 : Actor | name : "a62",movies : (1861, 1862, 1863) > 
<  1868 : Actress | name : "a63",movies : (1861, 1862, 1863, 1864) > 
<  1869 : Actress | name : "a64",movies : (1861, 1862, 1863, 1864) > 
<  1870 : Movie | rating : 6.5e+1 > 
<  1871 : Movie | rating : 6.6e+1 > 
<  1872 : Movie | rating : 6.7e+1 > 
<  1873 : Movie | rating : 6.8e+1 > 
<  1874 : Movie | rating : 6.9e+1 > 
<  1875 : Actor | name : "a65",movies : (1870, 1871) > 
<  1876 : Actor | name : "a66",movies : (1870, 1871, 1872) > 
<  1877 : Actress | name : "a67",movies : (1871, 1872, 1873) > 
<  1878 : Actress | name : "a68",movies : (1872, 1873, 1874) > 
<  1879 : Actress | name : "a69",movies : (1873, 1874) > 
<  1880 : Movie | rating : 5.0e+1 > 
<  1881 : Movie | rating : 5.1e+1 > 
<  1882 : Movie | rating : 5.2e+1 > 
<  1883 : Movie | rating : 5.3e+1 > 
<  1884 : Movie | rating : 5.4e+1 > 
<  1885 : Actor | name : "a50",movies : (1880, 1881, 1882, 1883) > 
<  1886 : Actor | name : "a51",movies : (1880, 1881, 1882, 1883) > 
<  1887 : Actor | name : "a52",movies : (1881, 1882, 1883) > 
<  1888 : Actress | name : "a53",movies : (1881, 1882, 1883, 1884) > 
<  1889 : Actress | name : "a54",movies : (1881, 1882, 1883, 1884) > 
<  1890 : Movie | rating : 5.5e+1 > 
<  1891 : Movie | rating : 5.6e+1 > 
<  1892 : Movie | rating : 5.7e+1 > 
<  1893 : Movie | rating : 5.8e+1 > 
<  1894 : Movie | rating : 5.9e+1 > 
<  1895 : Actor | name : "a55",movies : (1890, 1891) > 
<  1896 : Actor | name : "a56",movies : (1890, 1891, 1892) > 
<  1897 : Actress | name : "a57",movies : (1891, 1892, 1893) > 
<  1898 : Actress | name : "a58",movies : (1892, 1893, 1894) > 
<  1899 : Actress | name : "a59",movies : (1893, 1894) > 
<  1900 : Movie | rating : 4.0e+1 > 
<  1901 : Movie | rating : 4.1e+1 > 
<  1902 : Movie | rating : 4.2e+1 > 
<  1903 : Movie | rating : 4.3e+1 > 
<  1904 : Movie | rating : 4.4e+1 > 
<  1905 : Actor | name : "a40",movies : (1900, 1901, 1902, 1903) > 
<  1906 : Actor | name : "a41",movies : (1900, 1901, 1902, 1903) > 
<  1907 : Actor | name : "a42",movies : (1901, 1902, 1903) > 
<  1908 : Actress | name : "a43",movies : (1901, 1902, 1903, 1904) > 
<  1909 : Actress | name : "a44",movies : (1901, 1902, 1903, 1904) > 
<  1910 : Movie | rating : 4.5e+1 > 
<  1911 : Movie | rating : 4.6e+1 > 
<  1912 : Movie | rating : 4.7e+1 > 
<  1913 : Movie | rating : 4.8e+1 > 
<  1914 : Movie | rating : 4.9e+1 > 
<  1915 : Actor | name : "a45",movies : (1910, 1911) > 
<  1916 : Actor | name : "a46",movies : (1910, 1911, 1912) > 
<  1917 : Actress | name : "a47",movies : (1911, 1912, 1913) > 
<  1918 : Actress | name : "a48",movies : (1912, 1913, 1914) > 
<  1919 : Actress | name : "a49",movies : (1913, 1914) > 
<  1920 : Movie | rating : 3.0e+1 > 
<  1921 : Movie | rating : 3.1e+1 > 
<  1922 : Movie | rating : 3.2e+1 > 
<  1923 : Movie | rating : 3.3e+1 > 
<  1924 : Movie | rating : 3.4e+1 > 
<  1925 : Actor | name : "a30",movies : (1920, 1921, 1922, 1923) > 
<  1926 : Actor | name : "a31",movies : (1920, 1921, 1922, 1923) > 
<  1927 : Actor | name : "a32",movies : (1921, 1922, 1923) > 
<  1928 : Actress | name : "a33",movies : (1921, 1922, 1923, 1924) > 
<  1929 : Actress | name : "a34",movies : (1921, 1922, 1923, 1924) > 
<  1930 : Movie | rating : 3.5e+1 > 
<  1931 : Movie | rating : 3.6e+1 > 
<  1932 : Movie | rating : 3.7e+1 > 
<  1933 : Movie | rating : 3.8e+1 > 
<  1934 : Movie | rating : 3.9e+1 > 
<  1935 : Actor | name : "a35",movies : (1930, 1931) > 
<  1936 : Actor | name : "a36",movies : (1930, 1931, 1932) > 
<  1937 : Actress | name : "a37",movies : (1931, 1932, 1933) > 
<  1938 : Actress | name : "a38",movies : (1932, 1933, 1934) > 
<  1939 : Actress | name : "a39",movies : (1933, 1934) > 
<  1940 : Movie | rating : 2.0e+1 > 
<  1941 : Movie | rating : 2.1e+1 > 
<  1942 : Movie | rating : 2.2e+1 > 
<  1943 : Movie | rating : 2.3e+1 > 
<  1944 : Movie | rating : 2.4e+1 > 
<  1945 : Actor | name : "a20",movies : (1940, 1941, 1942, 1943) > 
<  1946 : Actor | name : "a21",movies : (1940, 1941, 1942, 1943) > 
<  1947 : Actor | name : "a22",movies : (1941, 1942, 1943) > 
<  1948 : Actress | name : "a23",movies : (1941, 1942, 1943, 1944) > 
<  1949 : Actress | name : "a24",movies : (1941, 1942, 1943, 1944) > 
<  1950 : Movie | rating : 2.5e+1 > 
<  1951 : Movie | rating : 2.6e+1 > 
<  1952 : Movie | rating : 2.7e+1 > 
<  1953 : Movie | rating : 2.8e+1 > 
<  1954 : Movie | rating : 2.9e+1 > 
<  1955 : Actor | name : "a25",movies : (1950, 1951) > 
<  1956 : Actor | name : "a26",movies : (1950, 1951, 1952) > 
<  1957 : Actress | name : "a27",movies : (1951, 1952, 1953) > 
<  1958 : Actress | name : "a28",movies : (1952, 1953, 1954) > 
<  1959 : Actress | name : "a29",movies : (1953, 1954) > 
<  1960 : Movie | rating : 1.0e+1 > 
<  1961 : Movie | rating : 1.1e+1 > 
<  1962 : Movie | rating : 1.2e+1 > 
<  1963 : Movie | rating : 1.3e+1 > 
<  1964 : Movie | rating : 1.4e+1 > 
<  1965 : Actor | name : "a10",movies : (1960, 1961, 1962, 1963) > 
<  1966 : Actor | name : "a11",movies : (1960, 1961, 1962, 1963) > 
<  1967 : Actor | name : "a12",movies : (1961, 1962, 1963) > 
<  1968 : Actress | name : "a13",movies : (1961, 1962, 1963, 1964) > 
<  1969 : Actress | name : "a14",movies : (1961, 1962, 1963, 1964) > 
<  1970 : Movie | rating : 1.5e+1 > 
<  1971 : Movie | rating : 1.6e+1 > 
<  1972 : Movie | rating : 1.7e+1 > 
<  1973 : Movie | rating : 1.8e+1 > 
<  1974 : Movie | rating : 1.9e+1 > 
<  1975 : Actor | name : "a15",movies : (1970, 1971) > 
<  1976 : Actor | name : "a16",movies : (1970, 1971, 1972) > 
<  1977 : Actress | name : "a17",movies : (1971, 1972, 1973) > 
<  1978 : Actress | name : "a18",movies : (1972, 1973, 1974) > 
<  1979 : Actress | name : "a19",movies : (1973, 1974) > 
<  1980 : Movie | rating : 0.0 > 
<  1981 : Movie | rating : 1.0 > 
<  1982 : Movie | rating : 2.0 > 
<  1983 : Movie | rating : 3.0 > 
<  1984 : Movie | rating : 4.0 > 
<  1985 : Actor | name : "a0",movies : (1980, 1981, 1982, 1983) > 
<  1986 : Actor | name : "a1",movies : (1980, 1981, 1982, 1983) > 
<  1987 : Actor | name : "a2",movies : (1981, 1982, 1983) > 
<  1988 : Actress | name : "a3",movies : (1981, 1982, 1983, 1984) > 
<  1989 : Actress | name : "a4",movies : (1981, 1982, 1983, 1984) > 
<  1990 : Movie | rating : 5.0 > 
<  1991 : Movie | rating : 6.0 > 
<  1992 : Movie | rating : 7.0 > 
<  1993 : Movie | rating : 8.0 > 
<  1994 : Movie | rating : 9.0 > 
<  1995 : Actor | name : "a5",movies : (1990, 1991) > 
<  1996 : Actor | name : "a6",movies : (1990, 1991, 1992) > 
<  1997 : Actress | name : "a7",movies : (1991, 1992, 1993) > 
<  1998 : Actress | name : "a8",movies : (1992, 1993, 1994) > 
<  1999 : Actress | name : "a9",movies : (1993, 1994) >
Bye.
