
load ../CommonFiles/mOdCL.maude
load ../CommonFiles/model-checker.maude
load ../CommonFiles/MGDefinitions.maude
load ../CommonFiles/MGRealTimeMaude24.maude
load ../CommonFiles/EcoreMM.maude
load ../CommonFiles/e-Motions.maude

load parameterwoven.ecore.maude
load Task3.behavior.maude
load inputModel/n2.xmi.maude

mod EJECUCION is
  protecting @MOVIES@BEHAVIOR@ .
  protecting OUT2 .

  op result1 : -> Set{@Object} .
  op s : -> Vid .
endm

---Simulation
rew init(out2) .

load ../quit.maude
